#!/usr/bin/env python3
import os

BASE = r"D:\temp\xlsx_work_pay\xl\worksheets"

def col_letter(n):
    result = ""
    while n > 0:
        n, rem = divmod(n - 1, 26)
        result = chr(65 + rem) + result
    return result

# ===== SHEET 4: 风险识别 =====
xml4 = ['<?xml version="1.0" encoding="UTF-8" standalone="yes"?>',
'<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">',
'  <sheetViews>',
'    <sheetView workbookViewId="0"/>',
'  </sheetViews>',
'  <sheetFormatPr defaultRowHeight="15" x14ac:dyDescent="0.25"',
'    xmlns:x14ac="http://schemas.microsoft.com/office/spreadsheetml/2009/9/ac"/>',
'  <cols>',
'    <col min="1" max="1" width="10" customWidth="1"/>',
'    <col min="2" max="2" width="24" customWidth="1"/>',
'    <col min="3" max="3" width="44" customWidth="1"/>',
'    <col min="4" max="4" width="14" customWidth="1"/>',
'  </cols>',
'  <sheetData>',
'    <row r="1">',
'      <c r="A1" t="inlineStr"><is><t>风险识别</t></is></c>',
'    </row>',
'    <row r="2">',
'      <c r="A2" t="inlineStr"><is><t>规则风险标记</t></is></c>',
'    </row>',
'    <row r="3">',
'      <c r="A3" t="inlineStr"><is><t>员工编号</t></is></c>',
'      <c r="B3" t="inlineStr"><is><t>风险项目</t></is></c>',
'      <c r="C3" t="inlineStr"><is><t>说明</t></is></c>',
'      <c r="D3" t="inlineStr"><is><t>风险等级</t></is></c>',
'    </row>',
'    <row r="4">',
'      <c r="A4" t="inlineStr"><is><t>E001</t></is></c>',
'      <c r="B4" t="inlineStr"><is><t>规则3：绩效与薪资脱节</t></is></c>',
'      <c r="C4" t="inlineStr"><is><t>绩效4分，薪资82000，低于市场水平</t></is></c>',
'      <c r="D4" t="inlineStr"><is><t>黄色</t></is></c>',
'    </row>',
'    <row r="5">',
'      <c r="A5" t="inlineStr"><is><t>E002</t></is></c>',
'      <c r="B5" t="inlineStr"><is><t>规则2：同岗不同薪</t></is></c>',
'      <c r="C5" t="inlineStr"><is><t>与E001同岗，薪资低3000元</t></is></c>',
'      <c r="D5" t="inlineStr"><is><t>黄色</t></is></c>',
'    </row>',
'    <row r="6">',
'      <c r="A6" t="inlineStr"><is><t>E003</t></is></c>',
'      <c r="B6" t="inlineStr"><is><t>无显著风险</t></is></c>',
'      <c r="D6" t="inlineStr"><is><t>绿色</t></is></c>',
'    </row>',
'    <row r="7">',
'      <c r="A7" t="inlineStr"><is><t>E004</t></is></c>',
'      <c r="B7" t="inlineStr"><is><t>规则4：长期未调薪</t></is></c>',
'      <c r="C7" t="inlineStr"><is><t>2年未调薪，薪资低于市场水平</t></is></c>',
'      <c r="D7" t="inlineStr"><is><t>黄色</t></is></c>',
'    </row>',
'    <row r="8">',
'      <c r="A8" t="inlineStr"><is><t>E005</t></is></c>',
'      <c r="B8" t="inlineStr"><is><t>无显著风险</t></is></c>',
'      <c r="D8" t="inlineStr"><is><t>绿色</t></is></c>',
'    </row>',
'    <row r="9">',
'      <c r="A9" t="inlineStr"><is><t>E006</t></is></c>',
'      <c r="B9" t="inlineStr"><is><t>无显著风险</t></is></c>',
'      <c r="D9" t="inlineStr"><is><t>绿色</t></is></c>',
'    </row>',
'    <row r="10">',
'      <c r="A10" t="inlineStr"><is><t>E007</t></is></c>',
'      <c r="B10" t="inlineStr"><is><t>规则1：新员工高起步</t></is></c>',
'      <c r="C10" t="inlineStr"><is><t>入职1年，薪资高于同等级</t></is></c>',
'      <c r="D10" t="inlineStr"><is><t>红色</t></is></c>',
'    </row>',
'    <row r="11">',
'      <c r="A11" t="inlineStr"><is><t>E008</t></is></c>',
'      <c r="B11" t="inlineStr"><is><t>无显著风险</t></is></c>',
'      <c r="D11" t="inlineStr"><is><t>绿色</t></is></c>',
'    </row>',
'    <row r="12">',
'      <c r="A12" t="inlineStr"><is><t>E009</t></is></c>',
'      <c r="B12" t="inlineStr"><is><t>无显著风险</t></is></c>',
'      <c r="D12" t="inlineStr"><is><t>绿色</t></is></c>',
'    </row>',
'    <row r="13">',
'      <c r="A13" t="inlineStr"><is><t>E010</t></is></c>',
'      <c r="B13" t="inlineStr"><is><t>规则4：长期未调薪</t></is></c>',
'      <c r="C13" t="inlineStr"><is><t>入职1年，薪资低于同岗水平</t></is></c>',
'      <c r="D13" t="inlineStr"><is><t>黄色</t></is></c>',
'    </row>',
'    <row r="14">',
'      <c r="A14" t="inlineStr"><is><t>E011</t></is></c>',
'      <c r="B14" t="inlineStr"><is><t>无显著风险</t></is></c>',
'      <c r="D14" t="inlineStr"><is><t>绿色</t></is></c>',
'    </row>',
'    <row r="15">',
'      <c r="A15" t="inlineStr"><is><t>E012</t></is></c>',
'      <c r="B15" t="inlineStr"><is><t>无显著风险</t></is></c>',
'      <c r="D15" t="inlineStr"><is><t>绿色</t></is></c>',
'    </row>',
'    <row r="16">',
'      <c r="A16" t="inlineStr"><is><t>E013</t></is></c>',
'      <c r="B16" t="inlineStr"><is><t>无显著风险</t></is></c>',
'      <c r="D16" t="inlineStr"><is><t>绿色</t></is></c>',
'    </row>',
'    <row r="17">',
'      <c r="A17" t="inlineStr"><is><t>E014</t></is></c>',
'      <c r="B17" t="inlineStr"><is><t>无显著风险</t></is></c>',
'      <c r="D17" t="inlineStr"><is><t>绿色</t></is></c>',
'    </row>',
'    <row r="18">',
'      <c r="A18" t="inlineStr"><is><t>E015</t></is></c>',
'      <c r="B18" t="inlineStr"><is><t>无显著风险</t></is></c>',
'      <c r="D18" t="inlineStr"><is><t>绿色</t></is></c>',
'    </row>',
'    <row r="19">',
'      <c r="A19" t="inlineStr"><is><t>E016</t></is></c>',
'      <c r="B19" t="inlineStr"><is><t>规则2：同岗不同薪</t></is></c>',
'      <c r="C19" t="inlineStr"><is><t>与E003同岗M4，薪资低23000元</t></is></c>',
'      <c r="D19" t="inlineStr"><is><t>红色</t></is></c>',
'    </row>',
'    <row r="20">',
'      <c r="A20" t="inlineStr"><is><t>E017</t></is></c>',
'      <c r="B20" t="inlineStr"><is><t>无显著风险</t></is></c>',
'      <c r="D20" t="inlineStr"><is><t>绿色</t></is></c>',
'    </row>',
'    <row r="21">',
'      <c r="A21" t="inlineStr"><is><t>E018</t></is></c>',
'      <c r="B21" t="inlineStr"><is><t>无显著风险</t></is></c>',
'      <c r="D21" t="inlineStr"><is><t>绿色</t></is></c>',
'    </row>',
'    <row r="22">',
'      <c r="A22" t="inlineStr"><is><t>E019</t></is></c>',
'      <c r="B22" t="inlineStr"><is><t>无显著风险</t></is></c>',
'      <c r="D22" t="inlineStr"><is><t>绿色</t></is></c>',
'    </row>',
'    <row r="23">',
'      <c r="A23" t="inlineStr"><is><t>E020</t></is></c>',
'      <c r="B23" t="inlineStr"><is><t>无显著风险</t></is></c>',
'      <c r="D23" t="inlineStr"><is><t>绿色</t></is></c>',
'    </row>',
'    <row r="24">',
'      <c r="A24" t="inlineStr"><is><t>E021</t></is></c>',
'      <c r="B24" t="inlineStr"><is><t>无显著风险</t></is></c>',
'      <c r="D24" t="inlineStr"><is><t>绿色</t></is></c>',
'    </row>',
'    <row r="25">',
'      <c r="A25" t="inlineStr"><is><t>E022</t></is></c>',
'      <c r="B25" t="inlineStr"><is><t>无显著风险</t></is></c>',
'      <c r="D25" t="inlineStr"><is><t>绿色</t></is></c>',
'    </row>',
'    <row r="27">',
'      <c r="A27" t="inlineStr"><is><t>风险等级说明</t></is></c>',
'    </row>',
'    <row r="28">',
'      <c r="A28" t="inlineStr"><is><t>绿色（低风险）</t></is></c>',
'      <c r="B28" t="inlineStr"><is><t>差距小于5%，无需立即行动，建议持续监控</t></is></c>',
'    </row>',
'    <row r="29">',
'      <c r="A29" t="inlineStr"><is><t>黄色（中等风险）</t></is></c>',
'      <c r="B29" t="inlineStr"><is><t>差距5%-10%，需调查原因，无合理解释需制定改善计划</t></is></c>',
'    </row>',
'    <row r="30">',
'      <c r="A30" t="inlineStr"><is><t>红色（高风险）</t></is></c>',
'      <c r="B30" t="inlineStr"><is><t>差距大于10%，需立即调查，必须有书面说明或改善计划</t></is></c>',
'    </row>',
'  </sheetData>',
'  <pageMargins left="0.7" right="0.7" top="0.75" bottom="0.75" header="0.3" footer="0.3"/>',
'</worksheet>']

with open(os.path.join(BASE, "sheet4.xml"), 'w', encoding='utf-8') as f:
    f.write('\n'.join(xml4))
print("Sheet 4 done")

# ===== SHEET 5: 风险报告 =====
xml5 = ['<?xml version="1.0" encoding="UTF-8" standalone="yes"?>',
'<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">',
'  <sheetViews>',
'    <sheetView workbookViewId="0"/>',
'  </sheetViews>',
'  <sheetFormatPr defaultRowHeight="15" x14ac:dyDescent="0.25"',
'    xmlns:x14ac="http://schemas.microsoft.com/office/spreadsheetml/2009/9/ac"/>',
'  <cols>',
'    <col min="1" max="1" width="24" customWidth="1"/>',
'    <col min="2" max="2" width="16" customWidth="1"/>',
'    <col min="3" max="3" width="20" customWidth="1"/>',
'  </cols>',
'  <sheetData>',
'    <row r="1">',
'      <c r="A1" t="inlineStr"><is><t>风险报告</t></is></c>',
'    </row>',
'    <row r="2">',
'      <c r="A2" t="inlineStr"><is><t>关键指标</t></is></c>',
'    </row>',
'    <row r="3">',
'      <c r="A3" t="inlineStr"><is><t>总员工数</t></is></c>',
'      <c r="B3" s="10"><f>COUNTA(团队数据输入!A:A)-1</f><v></v></c>',
'    </row>',
'    <row r="4">',
'      <c r="A4" t="inlineStr"><is><t>平均薪资</t></is></c>',
'      <c r="B4" s="6"><f>AVERAGE(团队数据输入!F:F)</f><v></v></c>',
'    </row>',
'    <row r="5">',
'      <c r="A5" t="inlineStr"><is><t>薪资中位数</t></is></c>',
'      <c r="B5" s="6"><f>MEDIAN(团队数据输入!F:F)</f><v></v></c>',
'    </row>',
'    <row r="6">',
'      <c r="A6" t="inlineStr"><is><t>整体薪酬差距（未调整）</t></is></c>',
'      <c r="B6" s="8"><f>(统计分!C4-统计分!C5)/统计分!C4</f><v></v></c>',
'    </row>',
'    <row r="7">',
'      <c r="A7" t="inlineStr"><is><t>整体薪酬差距（调整后）</t></is></c>',
'      <c r="B7" s="8"><f>统计分!F6</f><v></v></c>',
'    </row>',
'    <row r="8">',
'      <c r="A8" t="inlineStr"><is><t>高风险员工数</t></is></c>',
'      <c r="B8" s="10"><f>COUNTIF(风险识别!D:D,"红色")</f><v></v></c>',
'    </row>',
'    <row r="9">',
'      <c r="A9" t="inlineStr"><is><t>中风险员工数</t></is></c>',
'      <c r="B9" s="10"><f>COUNTIF(风险识别!D:D,"黄色")</f><v></v></c>',
'    </row>',
'    <row r="10">',
'      <c r="A10" t="inlineStr"><is><t>低风险员工数</t></is></c>',
'      <c r="B10" s="10"><f>COUNTIF(风险识别!D:D,"绿色")</f><v></v></c>',
'    </row>',
'    <row r="12">',
'      <c r="A12" t="inlineStr"><is><t>风险分布</t></is></c>',
'    </row>',
'    <row r="13">',
'      <c r="A13" t="inlineStr"><is><t>风险等级</t></is></c>',
'      <c r="B13" t="inlineStr"><is><t>人数</t></is></c>',
'      <c r="C13" t="inlineStr"><is><t>占比</t></is></c>',
'    </row>',
'    <row r="14">',
'      <c r="A14" t="inlineStr"><is><t>高风险（红色）</t></is></c>',
'      <c r="B14" s="10"><f>B8</f><v></v></c>',
'      <c r="C14" s="8"><f>B8/B3</f><v></v></c>',
'    </row>',
'    <row r="15">',
'      <c r="A15" t="inlineStr"><is><t>中风险（黄色）</t></is></c>',
'      <c r="B15" s="10"><f>B9</f><v></v></c>',
'      <c r="C15" s="8"><f>B9/B3</f><v></v></c>',
'    </row>',
'    <row r="16">',
'      <c r="A16" t="inlineStr"><is><t>低风险（绿色）</t></is></c>',
'      <c r="B16" s="10"><f>B10</f><v></v></c>',
'      <c r="C16" s="8"><f>B10/B3</f><v></v></c>',
'    </row>',
'    <row r="18">',
'      <c r="A18" t="inlineStr"><is><t>建议行动</t></is></c>',
'    </row>',
'    <row r="19">',
'      <c r="A19" t="inlineStr"><is><t>高风险行动</t></is></c>',
'      <c r="B19" t="inlineStr"><is><t>立即调查并制定改善计划，30天内完成</t></is></c>',
'    </row>',
'    <row r="20">',
'      <c r="A20" t="inlineStr"><is><t>中风险行动</t></is></c>',
'      <c r="B20" t="inlineStr"><is><t>深入分析原因，90天内制定改善方案</t></is></c>',
'    </row>',
'    <row r="21">',
'      <c r="A21" t="inlineStr"><is><t>低风险行动</t></is></c>',
'      <c r="B21" t="inlineStr"><is><t>纳入年度评审，持续监控</t></is></c>',
'    </row>',
'    <row r="23">',
'      <c r="A23" t="inlineStr"><is><t>签名/审批</t></is></c>',
'    </row>',
'    <row r="24">',
'      <c r="A24" t="inlineStr"><is><t>编制人</t></is></c>',
'      <c r="B24" t="inlineStr"><is><t></t></is></c>',
'    </row>',
'    <row r="25">',
'      <c r="A25" t="inlineStr"><is><t>审核人</t></is></c>',
'      <c r="B25" t="inlineStr"><is><t></t></is></c>',
'    </row>',
'    <row r="26">',
'      <c r="A26" t="inlineStr"><is><t>审批人</t></is></c>',
'      <c r="B26" t="inlineStr"><is><t></t></is></c>',
'    </row>',
'    <row r="27">',
'      <c r="A27" t="inlineStr"><is><t>日期</t></is></c>',
'      <c r="B27" t="inlineStr"><is><t>2026-08-10</t></is></c>',
'    </row>',
'  </sheetData>',
'  <pageMargins left="0.7" right="0.7" top="0.75" bottom="0.75" header="0.3" footer="0.3"/>',
'</worksheet>']

with open(os.path.join(BASE, "sheet5.xml"), 'w', encoding='utf-8') as f:
    f.write('\n'.join(xml5))
print("Sheet 5 done")

# ===== SHEET 6: 解读指南 =====
xml6 = ['<?xml version="1.0" encoding="UTF-8" standalone="yes"?>',
'<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">',
'  <sheetViews>',
'    <sheetView workbookViewId="0"/>',
'  </sheetViews>',
'  <sheetFormatPr defaultRowHeight="15" x14ac:dyDescent="0.25"',
'    xmlns:x14ac="http://schemas.microsoft.com/office/spreadsheetml/2009/9/ac"/>',
'  <cols>',
'    <col min="1" max="1" width="20" customWidth="1"/>',
'    <col min="2" max="2" width="60" customWidth="1"/>',
'  </cols>',
'  <sheetData>',
'    <row r="1">',
'      <c r="A1" t="inlineStr"><is><t>指标解读指南</t></is></c>',
'    </row>',
'    <row r="2">',
'      <c r="A2" t="inlineStr"><is><t>如何阅读每个指标</t></is></c>',
'    </row>',
'    <row r="3">',
'      <c r="A3" t="inlineStr"><is><t>薪资差距</t></is></c>',
'      <c r="B3" t="inlineStr"><is><t>表示两个群体间的平均薪资差异百分比。正值表示前者高于后者。</t></is></c>',
'    </row>',
'    <row r="4">',
'      <c r="A4" t="inlineStr"><is><t>绩效调整</t></is></c>',
'      <c r="B4" t="inlineStr"><is><t>控制绩效评分后的薪资比较，更公平地反映公平性问题。</t></is></c>',
'    </row>',
'    <row r="5">',
'      <c r="A5" t="inlineStr"><is><t>市场调整</t></is></c>',
'      <c r="B5" t="inlineStr"><is><t>与市场中位值比较，评估薪资外部竞争力。</t></is></c>',
'    </row>',
'    <row r="6">',
'      <c r="A6" t="inlineStr"><is><t>异常值标记</t></is></c>',
'      <c r="B6" t="inlineStr"><is><t>超出正常范围的个体，提示需进一步核查。</t></is></c>',
'    </row>',
'    <row r="7">',
'      <c r="A7" t="inlineStr"><is><t>统计显著性</t></is></c>',
'      <c r="B7" t="inlineStr"><is><t>P值小于0.05表示差距是统计显著的，不是随机波动。</t></is></c>',
'    </row>',
'    <row r="9">',
'      <c r="A9" t="inlineStr"><is><t>常见标志差异原因</t></is></c>',
'    </row>',
'    <row r="10">',
'      <c r="A10" t="inlineStr"><is><t>历史遗留</t></is></c>',
'      <c r="B10" t="inlineStr"><is><t>过去的决策累积效应</t></is></c>',
'    </row>',
'    <row r="11">',
'      <c r="A11" t="inlineStr"><is><t>岗位差异</t></is></c>',
'      <c r="B11" t="inlineStr"><is><t>职责范围或技能要求不同</t></is></c>',
'    </row>',
'    <row r="12">',
'      <c r="A12" t="inlineStr"><is><t>绩效周期</t></is></c>',
'      <c r="B12" t="inlineStr"><is><t>最近绩效评估时间不一致</t></is></c>',
'    </row>',
'    <row r="13">',
'      <c r="A13" t="inlineStr"><is><t>市场变化</t></is></c>',
'      <c r="B13" t="inlineStr"><is><t>市场薪资水平波动</t></is></c>',
'    </row>',
'    <row r="15">',
'      <c r="A15" t="inlineStr"><is><t>调查框架</t></is></c>',
'    </row>',
'    <row r="16">',
'      <c r="A16" t="inlineStr"><is><t>步骤1：确认数据准确性</t></is></c>',
'      <c r="B16" t="inlineStr"><is><t>核查输入数据是否正确，是否有遗漏或错误。</t></is></c>',
'    </row>',
'    <row r="17">',
'      <c r="A17" t="inlineStr"><is><t>步骤2：识别显著差距</t></is></c>',
'      <c r="B17" t="inlineStr"><is><t>使用统计方法确认差距是否具有显著性。</t></is></c>',
'    </row>',
'    <row r="18">',
'      <c r="A18" t="inlineStr"><is><t>步骤3：分析原因</t></is></c>',
'      <c r="B18" t="inlineStr"><is><t>考虑工作表现、经验、技能、市场状况等合理因素。</t></is></c>',
'    </row>',
'    <row r="19">',
'      <c r="A19" t="inlineStr"><is><t>步骤4：制定行动计划</t></is></c>',
'      <c r="B19" t="inlineStr"><is><t>如无法解释，制定改善计划并设定时间表。</t></is></c>',
'    </row>',
'    <row r="21">',
'      <c r="A21" t="inlineStr"><is><t>文档要求</t></is></c>',
'    </row>',
'    <row r="22">',
'      <c r="A22" t="inlineStr"><is><t>1</t></is></c>',
'      <c r="B22" t="inlineStr"><is><t>所有薪酬决策应有书面记录</t></is></c>',
'    </row>',
'    <row r="23">',
'      <c r="A23" t="inlineStr"><is><t>2</t></is></c>',
'      <c r="B23" t="inlineStr"><is><t>保存分析依据和决策理由</t></is></c>',
'    </row>',
'    <row r="24">',
'      <c r="A24" t="inlineStr"><is><t>3</t></is></c>',
'      <c r="B24" t="inlineStr"><is><t>定期更新市场数据</t></is></c>',
'    </row>',
'    <row r="25">',
'      <c r="A25" t="inlineStr"><is><t>4</t></is></c>',
'      <c r="B25" t="inlineStr"><is><t>记录改进措施和效果</t></is></c>',
'    </row>',
'  </sheetData>',
'  <pageMargins left="0.7" right="0.7" top="0.75" bottom="0.75" header="0.3" footer="0.3"/>',
'</worksheet>']

with open(os.path.join(BASE, "sheet6.xml"), 'w', encoding='utf-8') as f:
    f.write('\n'.join(xml6))
print("Sheet 6 done")
print("All sheets for workbook 1 complete!")

