#!/usr/bin/env python3
import os

BASE = r"D:\temp\xlsx_work_audit\xl\worksheets"

def col_letter(n):
    result = ""
    while n > 0:
        n, rem = divmod(n - 1, 26)
        result = chr(65 + rem) + result
    return result

# ===== SHEET 1: 年度概览 =====
s1 = ['<?xml version="1.0" encoding="UTF-8" standalone="yes"?>',
'<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">',
'  <sheetViews>',
'    <sheetView workbookViewId="0"/>',
'  </sheetViews>',
'  <sheetFormatPr defaultRowHeight="15" x14ac:dyDescent="0.25"',
'    xmlns:x14ac="http://schemas.microsoft.com/office/spreadsheetml/2009/9/ac"/>',
'  <cols>',
'    <col min="1" max="1" width="16" customWidth="1"/>',
'    <col min="2" max="2" width="20" customWidth="1"/>',
'    <col min="3" max="3" width="20" customWidth="1"/>',
'    <col min="4" max="4" width="20" customWidth="1"/>',
'    <col min="5" max="5" width="20" customWidth="1"/>',
'  </cols>',
'  <sheetData>',
'    <row r="1">',
'      <c r="A1" t="inlineStr"><is><t>年度审计计划概览</t></is></c>',
'    </row>',
'    <row r="2">',
'      <c r="A2" t="inlineStr"><is><t>算法审计与薪酬偏见治理 - 2026年度审计日历</t></is></c>',
'    </row>',
'    <row r="4">',
'      <c r="A4" t="inlineStr"><is><t>季度</t></is></c>',
'      <c r="B4" t="inlineStr"><is><t>阶段名称</t></is></c>',
'      <c r="C4" t="inlineStr"><is><t>关键里程碑</t></is></c>',
'      <c r="D4" t="inlineStr"><is><t>关键截止日</t></is></c>',
'      <c r="E4" t="inlineStr"><is><t>目标</t></is></c>',
'    </row>',
'    <row r="5">',
'      <c r="A5" t="inlineStr"><is><t>Q1</t></is></c>',
'      <c r="B5" t="inlineStr"><is><t>基础建设与数据收集</t></is></c>',
'      <c r="C5" t="inlineStr"><is><t>供应商文档审查完成</t></is></c>',
'      <c r="D5" t="inlineStr"><is><t>2026-03-31</t></is></c>',
'      <c r="E5" t="inlineStr"><is><t>建立审计基线，完成数据收集</t></is></c>',
'    </row>',
'    <row r="6">',
'      <c r="A6" t="inlineStr"><is><t>Q2</t></is></c>',
'      <c r="B6" t="inlineStr"><is><t>深度分析与改善规划</t></is></c>',
'      <c r="C6" t="inlineStr"><is><t>偏见测试完成</t></is></c>',
'      <c r="D6" t="inlineStr"><is><t>2026-06-30</t></is></c>',
'      <c r="E6" t="inlineStr"><is><t>完成深度分析，制定改善计划</t></is></c>',
'    </row>',
'    <row r="7">',
'      <c r="A7" t="inlineStr"><is><t>Q3</t></is></c>',
'      <c r="B7" t="inlineStr"><is><t>实施与持续监控</t></is></c>',
'      <c r="C7" t="inlineStr"><is><t>半年评估报告</t></is></c>',
'      <c r="D7" t="inlineStr"><is><t>2026-09-30</t></is></c>',
'      <c r="E7" t="inlineStr"><is><t>监控改善措施实施效果</t></is></c>',
'    </row>',
'    <row r="8">',
'      <c r="A8" t="inlineStr"><is><t>Q4</t></is></c>',
'      <c r="B8" t="inlineStr"><is><t>年终评估与规划</t></is></c>',
'      <c r="C8" t="inlineStr"><is><t>年度审计报告</t></is></c>',
'      <c r="D8" t="inlineStr"><is><t>2026-12-31</t></is></c>',
'      <c r="E8" t="inlineStr"><is><t>完成年终评估，规划下年度</t></is></c>',
'    </row>',
'    <row r="10">',
'      <c r="A10" t="inlineStr"><is><t>关键审计里程碑</t></is></c>',
'    </row>',
'    <row r="11">',
'      <c r="A11" t="inlineStr"><is><t>日期</t></is></c>',
'      <c r="B11" t="inlineStr"><is><t>里程碑</t></is></c>',
'    </row>',
'    <row r="12">',
'      <c r="A12" t="inlineStr"><is><t>2026-01-15</t></is></c>',
'      <c r="B12" t="inlineStr"><is><t>供应商文档审查截止</t></is></c>',
'    </row>',
'    <row r="13">',
'      <c r="A13" t="inlineStr"><is><t>2026-02-28</t></is></c>',
'      <c r="B13" t="inlineStr"><is><t>数据收集完成</t></is></c>',
'    </row>',
'    <row r="14">',
'      <c r="A14" t="inlineStr"><is><t>2026-03-31</t></is></c>',
'      <c r="B14" t="inlineStr"><is><t>Q1审计阶段完成</t></is></c>',
'    </row>',
'    <row r="15">',
'      <c r="A15" t="inlineStr"><is><t>2026-05-31</t></is></c>',
'      <c r="B15" t="inlineStr"><is><t>改善计划制定截止</t></is></c>',
'    </row>',
'    <row r="16">',
'      <c r="A16" t="inlineStr"><is><t>2026-06-30</t></is></c>',
'      <c r="B16" t="inlineStr"><is><t>Q2审计阶段完成</t></is></c>',
'    </row>',
'    <row r="17">',
'      <c r="A17" t="inlineStr"><is><t>2026-09-30</t></is></c>',
'      <c r="B17" t="inlineStr"><is><t>Q3审计阶段完成</t></is></c>',
'    </row>',
'    <row r="18">',
'      <c r="A18" t="inlineStr"><is><t>2026-11-30</t></is></c>',
'      <c r="B18" t="inlineStr"><is><t>年度审计报告提交</t></is></c>',
'    </row>',
'    <row r="19">',
'      <c r="A19" t="inlineStr"><is><t>2026-12-31</t></is></c>',
'      <c r="B19" t="inlineStr"><is><t>Q4及全年审计完成</t></is></c>',
'    </row>',
'  </sheetData>',
'  <pageMargins left="0.7" right="0.7" top="0.75" bottom="0.75" header="0.3" footer="0.3"/>',
'</worksheet>']

with open(os.path.join(BASE, "sheet1.xml"), 'w', encoding='utf-8') as f:
    f.write('\n'.join(s1))
print("Sheet 1 done")

# ===== SHEET 2: Q1审计计划 =====
s2 = ['<?xml version="1.0" encoding="UTF-8" standalone="yes"?>',
'<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">',
'  <sheetViews>',
'    <sheetView workbookViewId="0"/>',
'  </sheetViews>',
'  <sheetFormatPr defaultRowHeight="15" x14ac:dyDescent="0.25"',
'    xmlns:x14ac="http://schemas.microsoft.com/office/spreadsheetml/2009/9/ac"/>',
'  <cols>',
'    <col min="1" max="1" width="6" customWidth="1"/>',
'    <col min="2" max="2" width="28" customWidth="1"/>',
'    <col min="3" max="3" width="14" customWidth="1"/>',
'    <col min="4" max="4" width="14" customWidth="1"/>',
'    <col min="5" max="5" width="18" customWidth="1"/>',
'    <col min="6" max="6" width="10" customWidth="1"/>',
'  </cols>',
'  <sheetData>',
'    <row r="1">',
'      <c r="A1" t="inlineStr"><is><t>Q1审计计划 - 基础建设与数据收集</t></is></c>',
'    </row>',
'    <row r="2">',
'      <c r="A2" t="inlineStr"><is><t>January: 供应商文档审查 | February: 数据收集与基线建立 | March: 初步偏见测试</t></is></c>',
'    </row>',
'    <row r="4">',
'      <c r="A4" t="inlineStr"><is><t>序号</t></is></c>',
'      <c r="B4" t="inlineStr"><is><t>任务</t></is></c>',
'      <c r="C4" t="inlineStr"><is><t>负责人</t></is></c>',
'      <c r="D4" t="inlineStr"><is><t>截止日期</t></is></c>',
'      <c r="E4" t="inlineStr"><is><t>交付物</t></is></c>',
'      <c r="F4" t="inlineStr"><is><t>状态</t></is></c>',
'    </row>',
'    <row r="5">',
'      <c r="A5" t="inlineStr"><is><t>1</t></is></c>',
'      <c r="B5" t="inlineStr"><is><t>收集算法供应商资质文件</t></is></c>',
'      <c r="C5" t="inlineStr"><is><t>HR总监</t></is></c>',
'      <c r="D5" t="inlineStr"><is><t>2026-01-10</t></is></c>',
'      <c r="E5" t="inlineStr"><is><t>供应商资质清单</t></is></c>',
'      <c r="F5" t="inlineStr"><is><t>待开始</t></is></c>',
'    </row>',
'    <row r="6">',
'      <c r="A6" t="inlineStr"><is><t>2</t></is></c>',
'      <c r="B6" t="inlineStr"><is><t>审查算法透明度报告</t></is></c>',
'      <c r="C6" t="inlineStr"><is><t>合规官</t></is></c>',
'      <c r="D6" t="inlineStr"><is><t>2026-01-15</t></is></c>',
'      <c r="E6" t="inlineStr"><is><t>透明度评估报告</t></is></c>',
'      <c r="F6" t="inlineStr"><is><t>待开始</t></is></c>',
'    </row>',
'    <row r="7">',
'      <c r="A7" t="inlineStr"><is><t>3</t></is></c>',
'      <c r="B7" t="inlineStr"><is><t>确认数据处理协议</t></is></c>',
'      <c r="C7" t="inlineStr"><is><t>法务</t></is></c>',
'      <c r="D7" t="inlineStr"><is><t>2026-01-20</t></is></c>',
'      <c r="E7" t="inlineStr"><is><t>数据协议确认函</t></is></c>',
'      <c r="F7" t="inlineStr"><is><t>待开始</t></is></c>',
'    </row>',
'    <row r="8">',
'      <c r="A8" t="inlineStr"><is><t>4</t></is></c>',
'      <c r="B8" t="inlineStr"><is><t>收集历史薪酬数据</t></is></c>',
'      <c r="C8" t="inlineStr"><is><t>HR总监</t></is></c>',
'      <c r="D8" t="inlineStr"><is><t>2026-02-05</t></is></c>',
'      <c r="E8" t="inlineStr"><is><t>薪酬数据库</t></is></c>',
'      <c r="F8" t="inlineStr"><is><t>待开始</t></is></c>',
'    </row>',
'    <row r="9">',
'      <c r="A9" t="inlineStr"><is><t>5</t></is></c>',
'      <c r="B9" t="inlineStr"><is><t>建立绩效评分与薪资关联分析</t></is></c>',
'      <c r="C9" t="inlineStr"><is><t>HR总监</t></is></c>',
'      <c r="D9" t="inlineStr"><is><t>2026-02-15</t></is></c>',
'      <c r="E9" t="inlineStr"><is><t>绩效薪资分析模型</t></is></c>',
'      <c r="F9" t="inlineStr"><is><t>待开始</t></is></c>',
'    </row>',
'    <row r="10">',
'      <c r="A10" t="inlineStr"><is><t>6</t></is></c>',
'      <c r="B10" t="inlineStr"><is><t>验证数据完整性与准确性</t></is></c>',
'      <c r="C10" t="inlineStr"><is><t>IT</t></is></c>',
'      <c r="D10" t="inlineStr"><is><t>2026-02-20</t></is></c>',
'      <c r="E10" t="inlineStr"><is><t>数据质量报告</t></is></c>',
'      <c r="F10" t="inlineStr"><is><t>待开始</t></is></c>',
'    </row>',
'    <row r="11">',
'      <c r="A11" t="inlineStr"><is><t>7</t></is></c>',
'      <c r="B11" t="inlineStr"><is><t>建立审计基线指标</t></is></c>',
'      <c r="C11" t="inlineStr"><is><t>HR总监</t></is></c>',
'      <c r="D11" t="inlineStr"><is><t>2026-02-28</t></is></c>',
'      <c r="E11" t="inlineStr"><is><t>基线指标文档</t></is></c>',
'      <c r="F11" t="inlineStr"><is><t>待开始</t></is></c>',
'    </row>',
'    <row r="12">',
'      <c r="A12" t="inlineStr"><is><t>8</t></is></c>',
'      <c r="B12" t="inlineStr"><is><t>完成偏见测试初步模型</t></is></c>',
'      <c r="C12" t="inlineStr"><is><t>外部审计师</t></is></c>',
'      <c r="D12" t="inlineStr"><is><t>2026-03-10</t></is></c>',
'      <c r="E12" t="inlineStr"><is><t>偏见测试模型</t></is></c>',
'      <c r="F12" t="inlineStr"><is><t>待开始</t></is></c>',
'    </row>',
'    <row r="13">',
'      <c r="A13" t="inlineStr"><is><t>9</t></is></c>',
'      <c r="B13" t="inlineStr"><is><t>运行初始偏见检测</t></is></c>',
'      <c r="C13" t="inlineStr"><is><t>外部审计师</t></is></c>',
'      <c r="D13" t="inlineStr"><is><t>2026-03-20</t></is></c>',
'      <c r="E13" t="inlineStr"><is><t>初始偏见检测报告</t></is></c>',
'      <c r="F13" t="inlineStr"><is><t>待开始</t></is></c>',
'    </row>',
'    <row r="14">',
'      <c r="A14" t="inlineStr"><is><t>10</t></is></c>',
'      <c r="B14" t="inlineStr"><is><t>Q1阶段总结与Q2计划</t></is></c>',
'      <c r="C14" t="inlineStr"><is><t>HR总监</t></is></c>',
'      <c r="D14" t="inlineStr"><is><t>2026-03-31</t></is></c>',
'      <c r="E14" t="inlineStr"><is><t>Q1总结报告</t></is></c>',
'      <c r="F14" t="inlineStr"><is><t>待开始</t></is></c>',
'    </row>',
'    <row r="16">',
'      <c r="A16" t="inlineStr"><is><t>Q1关键成果</t></is></c>',
'    </row>',
'    <row r="17">',
'      <c r="A17" t="inlineStr"><is><t>完成供应商文档审查</t></is></c>',
'    </row>',
'    <row r="18">',
'      <c r="A18" t="inlineStr"><is><t>建立完整薪酬数据集</t></is></c>',
'    </row>',
'    <row r="19">',
'      <c r="A19" t="inlineStr"><is><t>完成初步偏见检测并识别高风险区域</t></is></c>',
'    </row>',
'  </sheetData>',
'  <pageMargins left="0.7" right="0.7" top="0.75" bottom="0.75" header="0.3" footer="0.3"/>',
'</worksheet>']

with open(os.path.join(BASE, "sheet2.xml"), 'w', encoding='utf-8') as f:
    f.write('\n'.join(s2))
print("Sheet 2 done")

# ===== SHEET 3: Q2审计计划 =====
s3 = ['<?xml version="1.0" encoding="UTF-8" standalone="yes"?>',
'<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">',
'  <sheetViews>',
'    <sheetView workbookViewId="0"/>',
'  </sheetViews>',
'  <sheetFormatPr defaultRowHeight="15" x14ac:dyDescent="0.25"',
'    xmlns:x14ac="http://schemas.microsoft.com/office/spreadsheetml/2009/9/ac"/>',
'  <cols>',
'    <col min="1" max="1" width="6" customWidth="1"/>',
'    <col min="2" max="2" width="28" customWidth="1"/>',
'    <col min="3" max="3" width="14" customWidth="1"/>',
'    <col min="4" max="4" width="14" customWidth="1"/>',
'    <col min="5" max="5" width="18" customWidth="1"/>',
'    <col min="6" max="6" width="10" customWidth="1"/>',
'  </cols>',
'  <sheetData>',
'    <row r="1">',
'      <c r="A1" t="inlineStr"><is><t>Q2审计计划 - 深度分析与改善规划</t></is></c>',
'    </row>',
'    <row r="2">',
'      <c r="A2" t="inlineStr"><is><t>April: 深度分析 | May: 改善规划 | June: 中期报告</t></is></c>',
'    </row>',
'    <row r="4">',
'      <c r="A4" t="inlineStr"><is><t>序号</t></is></c>',
'      <c r="B4" t="inlineStr"><is><t>任务</t></is></c>',
'      <c r="C4" t="inlineStr"><is><t>负责人</t></is></c>',
'      <c r="D4" t="inlineStr"><is><t>截止日期</t></is></c>',
'      <c r="E4" t="inlineStr"><is><t>交付物</t></is></c>',
'      <c r="F4" t="inlineStr"><is><t>状态</t></is></c>',
'    </row>',
'    <row r="5">',
'      <c r="A5" t="inlineStr"><is><t>1</t></is></c>',
'      <c r="B5" t="inlineStr"><is><t>完成深度偏见分析</t></is></c>',
'      <c r="C5" t="inlineStr"><is><t>外部审计师</t></is></c>',
'      <c r="D5" t="inlineStr"><is><t>2026-04-15</t></is></c>',
'      <c r="E5" t="inlineStr"><is><t>深度分析报告</t></is></c>',
'      <c r="F5" t="inlineStr"><is><t>待开始</t></is></c>',
'    </row>',
'    <row r="6">',
'      <c r="A6" t="inlineStr"><is><t>2</t></is></c>',
'      <c r="B6" t="inlineStr"><is><t>识别高风险薪酬差距</t></is></c>',
'      <c r="C6" t="inlineStr"><is><t>HR总监</t></is></c>',
'      <c r="D6" t="inlineStr"><is><t>2026-04-20</t></is></c>',
'      <c r="E6" t="inlineStr"><is><t>高风险差距清单</t></is></c>',
'      <c r="F6" t="inlineStr"><is><t>待开始</t></is></c>',
'    </row>',
'    <row r="7">',
'      <c r="A7" t="inlineStr"><is><t>3</t></is></c>',
'      <c r="B7" t="inlineStr"><is><t>分析差距根本原因</t></is></c>',
'      <c r="C7" t="inlineStr"><is><t>HR总监</t></is></c>',
'      <c r="D7" t="inlineStr"><is><t>2026-04-30</t></is></c>',
'      <c r="E7" t="inlineStr"><is><t>原因分析报告</t></is></c>',
'      <c r="F7" t="inlineStr"><is><t>待开始</t></is></c>',
'    </row>',
'    <row r="8">',
'      <c r="A8" t="inlineStr"><is><t>4</t></is></c>',
'      <c r="B8" t="inlineStr"><is><t>制定改善措施建议</t></is></c>',
'      <c r="C8" t="inlineStr"><is><t>HR总监</t></is></c>',
'      <c r="D8" t="inlineStr"><is><t>2026-05-10</t></is></c>',
'      <c r="E8" t="inlineStr"><is><t>改善建议清单</t></is></c>',
'      <c r="F8" t="inlineStr"><is><t>待开始</t></is></c>',
'    </row>',
'    <row r="9">',
'      <c r="A9" t="inlineStr"><is><t>5</t></is></c>',
'      <c r="B9" t="inlineStr"><is><t>估算改善成本</t></is></c>',
'      <c r="C9" t="inlineStr"><is><t>财务</t></is></c>',
'      <c r="D9" t="inlineStr"><is><t>2026-05-15</t></is></c>',
'      <c r="E9" t="inlineStr"><is><t>成本估算表</t></is></c>',
'      <c r="F9" t="inlineStr"><is><t>待开始</t></is></c>',
'    </row>',
'    <row r="10">',
'      <c r="A10" t="inlineStr"><is><t>6</t></is></c>',
'      <c r="B10" t="inlineStr"><is><t>制定改善计划时间表</t></is></c>',
'      <c r="C10" t="inlineStr"><is><t>HR总监</t></is></c>',
'      <c r="D10" t="inlineStr"><is><t>2026-05-20</t></is></c>',
'      <c r="E10" t="inlineStr"><is><t>改善计划时间表</t></is></c>',
'      <c r="F10" t="inlineStr"><is><t>待开始</t></is></c>',
'    </row>',
'    <row r="11">',
'      <c r="A11" t="inlineStr"><is><t>7</t></is></c>',
'      <c r="B11" t="inlineStr"><is><t>与利益相关方沟通改善计划</t></is></c>',
'      <c r="C11" t="inlineStr"><is><t>HR总监</t></is></c>',
'      <c r="D11" t="inlineStr"><is><t>2026-05-25</t></is></c>',
'      <c r="E11" t="inlineStr"><is><t>沟通纪要</t></is></c>',
'      <c r="F11" t="inlineStr"><is><t>待开始</t></is></c>',
'    </row>',
'    <row r="12">',
'      <c r="A12" t="inlineStr"><is><t>8</t></is></c>',
'      <c r="B12" t="inlineStr"><is><t>完成改善计划定稿</t></is></c>',
'      <c r="C12" t="inlineStr"><is><t>HR总监</t></is></c>',
'      <c r="D12" t="inlineStr"><is><t>2026-05-31</t></is></c>',
'      <c r="E12" t="inlineStr"><is><t>改善计划文档</t></is></c>',
'      <c r="F12" t="inlineStr"><is><t>待开始</t></is></c>',
'    </row>',
'    <row r="13">',
'      <c r="A13" t="inlineStr"><is><t>9</t></is></c>',
'      <c r="B13" t="inlineStr"><is><t>编制中期审计报告</t></is></c>',
'      <c r="C13" t="inlineStr"><is><t>合规官</t></is></c>',
'      <c r="D13" t="inlineStr"><is><t>2026-06-15</t></is></c>',
'      <c r="E13" t="inlineStr"><is><t>中期审计报告</t></is></c>',
'      <c r="F13" t="inlineStr"><is><t>待开始</t></is></c>',
'    </row>',
'    <row r="14">',
'      <c r="A14" t="inlineStr"><is><t>10</t></is></c>',
'      <c r="B14" t="inlineStr"><is><t>Q2阶段总结与Q3计划</t></is></c>',
'      <c r="C14" t="inlineStr"><is><t>HR总监</t></is></c>',
'      <c r="D14" t="inlineStr"><is><t>2026-06-30</t></is></c>',
'      <c r="E14" t="inlineStr"><is><t>Q2总结报告</t></is></c>',
'      <c r="F14" t="inlineStr"><is><t>待开始</t></is></c>',
'    </row>',
'    <row r="16">',
'      <c r="A16" t="inlineStr"><is><t>Q2关键成果</t></is></c>',
'    </row>',
'    <row r="17">',
'      <c r="A17" t="inlineStr"><is><t>完成深度偏见分析</t></is></c>',
'    </row>',
'    <row r="18">',
'      <c r="A18" t="inlineStr"><is><t>制定改善计划并获得批准</t></is></c>',
'    </row>',
'    <row r="19">',
'      <c r="A19" t="inlineStr"><is><t>完成中期审计报告提交</t></is></c>',
'    </row>',
'  </sheetData>',
'  <pageMargins left="0.7" right="0.7" top="0.75" bottom="0.75" header="0.3" footer="0.3"/>',
'</worksheet>']

with open(os.path.join(BASE, "sheet3.xml"), 'w', encoding='utf-8') as f:
    f.write('\n'.join(s3))
print("Sheet 3 done")

# ===== SHEET 4: Q3审计计划 =====
s4 = ['<?xml version="1.0" encoding="UTF-8" standalone="yes"?>',
'<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">',
'  <sheetViews>',
'    <sheetView workbookViewId="0"/>',
'  </sheetViews>',
'  <sheetFormatPr defaultRowHeight="15" x14ac:dyDescent="0.25"',
'    xmlns:x14ac="http://schemas.microsoft.com/office/spreadsheetml/2009/9/ac"/>',
'  <cols>',
'    <col min="1" max="1" width="6" customWidth="1"/>',
'    <col min="2" max="2" width="28" customWidth="1"/>',
'    <col min="3" max="3" width="14" customWidth="1"/>',
'    <col min="4" max="4" width="14" customWidth="1"/>',
'    <col min="5" max="5" width="18" customWidth="1"/>',
'    <col min="6" max="6" width="10" customWidth="1"/>',
'  </cols>',
'  <sheetData>',
'    <row r="1">',
'      <c r="A1" t="inlineStr"><is><t>Q3审计计划 - 实施与持续监控</t></is></c>',
'    </row>',
'    <row r="2">',
'      <c r="A2" t="inlineStr"><is><t>July: 实施监控 | August: 持续审计 | September: 半年评审</t></is></c>',
'    </row>',
'    <row r="4">',
'      <c r="A4" t="inlineStr"><is><t>序号</t></is></c>',
'      <c r="B4" t="inlineStr"><is><t>任务</t></is></c>',
'      <c r="C4" t="inlineStr"><is><t>负责人</t></is></c>',
'      <c r="D4" t="inlineStr"><is><t>截止日期</t></is></c>',
'      <c r="E4" t="inlineStr"><is><t>交付物</t></is></c>',
'      <c r="F4" t="inlineStr"><is><t>状态</t></is></c>',
'    </row>',
'    <row r="5">',
'      <c r="A5" t="inlineStr"><is><t>1</t></is></c>',
'      <c r="B5" t="inlineStr"><is><t>启动改善措施实施</t></is></c>',
'      <c r="C5" t="inlineStr"><is><t>HR总监</t></is></c>',
'      <c r="D5" t="inlineStr"><is><t>2026-07-05</t></is></c>',
'      <c r="E5" t="inlineStr"><is><t>启动确认函</t></is></c>',
'      <c r="F5" t="inlineStr"><is><t>待开始</t></is></c>',
'    </row>',
'    <row r="6">',
'      <c r="A6" t="inlineStr"><is><t>2</t></is></c>',
'      <c r="B6" t="inlineStr"><is><t>建立实时监控仪表板</t></is></c>',
'      <c r="C6" t="inlineStr"><is><t>IT</t></is></c>',
'      <c r="D6" t="inlineStr"><is><t>2026-07-15</t></is></c>',
'      <c r="E6" t="inlineStr"><is><t>监控仪表板</t></is></c>',
'      <c r="F6" t="inlineStr"><is><t>待开始</t></is></c>',
'    </row>',
'    <row r="7">',
'      <c r="A7" t="inlineStr"><is><t>3</t></is></c>',
'      <c r="B7" t="inlineStr"><is><t>每月偏见指标追踪</t></is></c>',
'      <c r="C7" t="inlineStr"><is><t>合规官</t></is></c>',
'      <c r="D7" t="inlineStr"><is><t>2026-07-31</t></is></c>',
'      <c r="E7" t="inlineStr"><is><t>月度追踪报告</t></is></c>',
'      <c r="F7" t="inlineStr"><is><t>待开始</t></is></c>',
'    </row>',
'    <row r="8">',
'      <c r="A8" t="inlineStr"><is><t>4</t></is></c>',
'      <c r="B8" t="inlineStr"><is><t>进行算法公平性培训</t></is></c>',
'      <c r="C8" t="inlineStr"><is><t>HR总监</t></is></c>',
'      <c r="D8" t="inlineStr"><is><t>2026-08-10</t></is></c>',
'      <c r="E8" t="inlineStr"><is><t>培训记录</t></is></c>',
'      <c r="F8" t="inlineStr"><is><t>待开始</t></is></c>',
'    </row>',
'    <row r="9">',
'      <c r="A9" t="inlineStr"><is><t>5</t></is></c>',
'      <c r="B9" t="inlineStr"><is><t>第二次偏见检测</t></is></c>',
'      <c r="C9" t="inlineStr"><is><t>外部审计师</t></is></c>',
'      <c r="D9" t="inlineStr"><is><t>2026-08-20</t></is></c>',
'      <c r="E9" t="inlineStr"><is><t>偏见检测报告v2</t></is></c>',
'      <c r="F9" t="inlineStr"><is><t>待开始</t></is></c>',
'    </row>',
'    <row r="10">',
'      <c r="A10" t="inlineStr"><is><t>6</t></is></c>',
'      <c r="B10" t="inlineStr"><is><t>评估改善措施效果</t></is></c>',
'      <c r="C10" t="inlineStr"><is><t>HR总监</t></is></c>',
'      <c r="D10" t="inlineStr"><is><t>2026-08-31</t></is></c>',
'      <c r="E10" t="inlineStr"><is><t>效果评估报告</t></is></c>',
'      <c r="F10" t="inlineStr"><is><t>待开始</t></is></c>',
'    </row>',
'    <row r="11">',
'      <c r="A11" t="inlineStr"><is><t>7</t></is></c>',
'      <c r="B11" t="inlineStr"><is><t>收集利益相关方反馈</t></is></c>',
'      <c r="C11" t="inlineStr"><is><t>HR总监</t></is></c>',
'      <c r="D11" t="inlineStr"><is><t>2026-09-10</t></is></c>',
'      <c r="E11" t="inlineStr"><is><t>反馈汇总</t></is></c>',
'      <c r="F11" t="inlineStr"><is><t>待开始</t></is></c>',
'    </row>',
'    <row r="12">',
'      <c r="A12" t="inlineStr"><is><t>8</t></is></c>',
'      <c r="B12" t="inlineStr"><is><t>调整改善计划（如需要）</t></is></c>',
'      <c r="C12" t="inlineStr"><is><t>HR总监</t></is></c>',
'      <c r="D12" t="inlineStr"><is><t>2026-09-15</t></is></c>',
'      <c r="E12" t="inlineStr"><is><t>调整后计划</t></is></c>',
'      <c r="F12" t="inlineStr"><is><t>待开始</t></is></c>',
'    </row>',
'    <row r="13">',
'      <c r="A13" t="inlineStr"><is><t>9</t></is></c>',
'      <c r="B13" t="inlineStr"><is><t>编制半年评估报告</t></is></c>',
'      <c r="C13" t="inlineStr"><is><t>合规官</t></is></c>',
'      <c r="D13" t="inlineStr"><is><t>2026-09-20</t></is></c>',
'      <c r="E13" t="inlineStr"><is><t>半年评估报告</t></is></c>',
'      <c r="F13" t="inlineStr"><is><t>待开始</t></is></c>',
'    </row>',
'    <row r="14">',
'      <c r="A14" t="inlineStr"><is><t>10</t></is></c>',
'      <c r="B14" t="inlineStr"><is><t>Q3阶段总结与Q4计划</t></is></c>',
'      <c r="C14" t="inlineStr"><is><t>HR总监</t></is></c>',
'      <c r="D14" t="inlineStr"><is><t>2026-09-30</t></is></c>',
'      <c r="E14" t="inlineStr"><is><t>Q3总结报告</t></is></c>',
'      <c r="F14" t="inlineStr"><is><t>待开始</t></is></c>',
'    </row>',
'    <row r="16">',
'      <c r="A16" t="inlineStr"><is><t>Q3关键成果</t></is></c>',
'    </row>',
'    <row r="17">',
'      <c r="A17" t="inlineStr"><is><t>改善措施实施率超过50%</t></is></c>',
'    </row>',
'    <row r="18">',
'      <c r="A18" t="inlineStr"><is><t>建立实时监控能力</t></is></c>',
'    </row>',
'    <row r="19">',
'      <c r="A19" t="inlineStr"><is><t>完成半年评估报告</t></is></c>',
'    </row>',
'  </sheetData>',
'  <pageMargins left="0.7" right="0.7" top="0.75" bottom="0.75" header="0.3" footer="0.3"/>',
'</worksheet>']

with open(os.path.join(BASE, "sheet4.xml"), 'w', encoding='utf-8') as f:
    f.write('\n'.join(s4))
print("Sheet 4 done")

# ===== SHEET 5: Q4审计计划 =====
s5 = ['<?xml version="1.0" encoding="UTF-8" standalone="yes"?>',
'<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">',
'  <sheetViews>',
'    <sheetView workbookViewId="0"/>',
'  </sheetViews>',
'  <sheetFormatPr defaultRowHeight="15" x14ac:dyDescent="0.25"',
'    xmlns:x14ac="http://schemas.microsoft.com/office/spreadsheetml/2009/9/ac"/>',
'  <cols>',
'    <col min="1" max="1" width="6" customWidth="1"/>',
'    <col min="2" max="2" width="28" customWidth="1"/>',
'    <col min="3" max="3" width="14" customWidth="1"/>',
'    <col min="4" max="4" width="14" customWidth="1"/>',
'    <col min="5" max="5" width="18" customWidth="1"/>',
'    <col min="6" max="6" width="10" customWidth="1"/>',
'  </cols>',
'  <sheetData>',
'    <row r="1">',
'      <c r="A1" t="inlineStr"><is><t>Q4审计计划 - 年终评估与规划</t></is></c>',
'    </row>',
'    <row r="2">',
'      <c r="A2" t="inlineStr"><is><t>October: 年终评估 | November: 最终报告 | December: 下年度规划</t></is></c>',
'    </row>',
'    <row r="4">',
'      <c r="A4" t="inlineStr"><is><t>序号</t></is></c>',
'      <c r="B4" t="inlineStr"><is><t>任务</t></is></c>',
'      <c r="C4" t="inlineStr"><is><t>负责人</t></is></c>',
'      <c r="D4" t="inlineStr"><is><t>截止日期</t></is></c>',
'      <c r="E4" t="inlineStr"><is><t>交付物</t></is></c>',
'      <c r="F4" t="inlineStr"><is><t>状态</t></is></c>',
'    </row>',
'    <row r="5">',
'      <c r="A5" t="inlineStr"><is><t>1</t></is></c>',
'      <c r="B5" t="inlineStr"><is><t>完成改善措施最终实施</t></is></c>',
'      <c r="C5" t="inlineStr"><is><t>HR总监</t></is></c>',
'      <c r="D5" t="inlineStr"><is><t>2026-10-15</t></is></c>',
'      <c r="E5" t="inlineStr"><is><t>实施完成确认</t></is></c>',
'      <c r="F5" t="inlineStr"><is><t>待开始</t></is></c>',
'    </row>',
'    <row r="6">',
'      <c r="A6" t="inlineStr"><is><t>2</t></is></c>',
'      <c r="B6" t="inlineStr"><is><t>年终偏见检测</t></is></c>',
'      <c r="C6" t="inlineStr"><is><t>外部审计师</t></is></c>',
'      <c r="D6" t="inlineStr"><is><t>2026-10-25</t></is></c>',
'      <c r="E6" t="inlineStr"><is><t>年终偏见检测报告</t></is></c>',
'      <c r="F6" t="inlineStr"><is><t>待开始</t></is></c>',
'    </row>',
'    <row r="7">',
'      <c r="A7" t="inlineStr"><is><t>3</t></is></c>',
'    <row r="7">',
'      <c r="A7" t="inlineStr"><is><t>3</t></is></c>',
'      <c r="B7" t="inlineStr"><is><t>评估年度改善效果</t></is></c>',
'      <c r="C7" t="inlineStr"><is><t>HR总监</t></is></c>',
'      <c r="D7" t="inlineStr"><is><t>2026-10-31</t></is></c>',
'      <c r="E7" t="inlineStr"><is><t>年度效果评估</t></is></c>',
'      <c r="F7" t="inlineStr"><is><t>待开始</t></is></c>',
'    </row>',
'    <row r="8">',
'      <c r="A8" t="inlineStr"><is><t>4</t></is></c>',
'      <c r="B8" t="inlineStr"><is><t>准备审计文档归档</t></is></c>',
'      <c r="C8" t="inlineStr"><is><t>合规官</t></is></c>',
'      <c r="D8" t="inlineStr"><is><t>2026-11-10</t></is></c>',
'      <c r="E8" t="inlineStr"><is><t>归档文档包</t></is></c>',
'      <c r="F8" t="inlineStr"><is><t>待开始</t></is></c>',
'    </row>',
'    <row r="9">',
'      <c r="A9" t="inlineStr"><is><t>5</t></is></c>',
'      <c r="B9" t="inlineStr"><is><t>编制年度审计报告</t></is></c>',
'      <c r="C9" t="inlineStr"><is><t>合规官</t></is></c>',
'      <c r="D9" t="inlineStr"><is><t>2026-11-20</t></is></c>',
'      <c r="E9" t="inlineStr"><is><t>年度审计报告</t></is></c>',
'      <c r="F9" t="inlineStr"><is><t>待开始</t></is></c>',
'    </row>',
'    <row r="10">',
'      <c r="A10" t="inlineStr"><is><t>6</t></is></c>',
'      <c r="B10" t="inlineStr"><is><t>管理评审</t></is></c>',
'      <c r="C10" t="inlineStr"><is><t>HR总监</t></is></c>',
'      <c r="D10" t="inlineStr"><is><t>2026-11-25</t></is></c>',
'      <c r="E10" t="inlineStr"><is><t>评审会议纪要</t></is></c>',
'      <c r="F10" t="inlineStr"><is><t>待开始</t></is></c>',
'    </row>',
'    <row r="11">',
'      <c r="A11" t="inlineStr"><is><t>7</t></is></c>',
'      <c r="B11" t="inlineStr"><is><t>提交最终报告</t></is></c>',
'      <c r="C11" t="inlineStr"><is><t>合规官</t></is></c>',
'      <c r="D11" t="inlineStr"><is><t>2026-11-30</t></is></c>',
'      <c r="E11" t="inlineStr"><is><t>最终报告</t></is></c>',
'      <c r="F11" t="inlineStr"><is><t>待开始</t></is></c>',
'    </row>',
'    <row r="12">',
'      <c r="A12" t="inlineStr"><is><t>8</t></is></c>',
'      <c r="B12" t="inlineStr"><is><t>制定下年度审计计划</t></is></c>',
'      <c r="C12" t="inlineStr"><is><t>HR总监</t></is></c>',
'      <c r="D12" t="inlineStr"><is><t>2026-12-15</t></is></c>',
'      <c r="E12" t="inlineStr"><is><t>下年度计划草案</t></is></c>',
'      <c r="F12" t="inlineStr"><is><t>待开始</t></is></c>',
'    </row>',
'    <row r="13">',
'      <c r="A13" t="inlineStr"><is><t>9</t></is></c>',
'      <c r="B13" t="inlineStr"><is><t>更新政策和流程</t></is></c>',
'      <c r="C13" t="inlineStr"><is><t>合规官</t></is></c>',
'      <c r="D13" t="inlineStr"><is><t>2026-12-20</t></is></c>',
'      <c r="E13" t="inlineStr"><is><t>更新后政策文档</t></is></c>',
'      <c r="F13" t="inlineStr"><is><t>待开始</t></is></c>',
'    </row>',
'    <row r="14">',
'      <c r="A14" t="inlineStr"><is><t>10</t></is></c>',
'      <c r="B14" t="inlineStr"><is><t>Q4及全年审计总结</t></is></c>',
'      <c r="C14" t="inlineStr"><is><t>HR总监</t></is></c>',
'      <c r="D14" t="inlineStr"><is><t>2026-12-31</t></is></c>',
'      <c r="E14" t="inlineStr"><is><t>全年总结报告</t></is></c>',
'      <c r="F14" t="inlineStr"><is><t>待开始</t></is></c>',
'    </row>',
'    <row r="16">',
'      <c r="A16" t="inlineStr"><is><t>Q4关键成果</t></is></c>',
'    </row>',
'    <row r="17">',
'      <c r="A17" t="inlineStr"><is><t>完成年度审计报告</t></is></c>',
'    </row>',
'    <row r="18">',
'      <c r="A18" t="inlineStr"><is><t>改善措施实施率达80%以上</t></is></c>',
'    </row>',
'    <row r="19">',
'      <c r="A19" t="inlineStr"><is><t>完成下年度审计计划制定</t></is></c>',
'    </row>',
'  </sheetData>',
'  <pageMargins left="0.7" right="0.7" top="0.75" bottom="0.75" header="0.3" footer="0.3"/>',
'</worksheet>']

with open(os.path.join(BASE, "sheet5.xml"), 'w', encoding='utf-8') as f:
    f.write('\n'.join(s5))
print("Sheet 5 done")

# ===== SHEET 6: RACI矩阵 =====
s6 = ['<?xml version="1.0" encoding="UTF-8" standalone="yes"?>',
'<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">',
'  <sheetViews>',
'    <sheetView workbookViewId="0"/>',
'  </sheetViews>',
'  <sheetFormatPr defaultRowHeight="15" x14ac:dyDescent="0.25"',
'    xmlns:x14ac="http://schemas.microsoft.com/office/spreadsheetml/2009/9/ac"/>',
'  <cols>',
'    <col min="1" max="1" width="28" customWidth="1"/>',
'    <col min="2" max="2" width="14" customWidth="1"/>',
'    <col min="3" max="3" width="14" customWidth="1"/>',
'    <col min="4" max="4" width="10" customWidth="1"/>',
'    <col min="5" max="5" width="10" customWidth="1"/>',
'    <col min="6" max="6" width="10" customWidth="1"/>',
'    <col min="7" max="7" width="14" customWidth="1"/>',
'  </cols>',
'  <sheetData>',
'    <row r="1">',
'      <c r="A1" t="inlineStr"><is><t>RACI矩阵 - 任务责任分配</t></is></c>',
'    </row>',
'    <row r="2">',
'      <c r="A2" t="inlineStr"><is><t>R=负责执行 A=最终问责 I=需知会 C=需咨询</t></is></c>',
'    </row>',
'    <row r="4">',
'      <c r="A4" t="inlineStr"><is><t>审计活动</t></is></c>',
'      <c r="B4" t="inlineStr"><is><t>HR总监</t></is></c>',
'      <c r="C4" t="inlineStr"><is><t>合规官</t></is></c>',
'      <c r="D4" t="inlineStr"><is><t>IT</t></is></c>',
'      <c r="E4" t="inlineStr"><is><t>财务</t></is></c>',
'      <c r="F4" t="inlineStr"><is><t>法务</t></is></c>',
'      <c r="G4" t="inlineStr"><is><t>外部审计师</t></is></c>',
'    </row>',
'    <row r="5">',
'      <c r="A5" t="inlineStr"><is><t>供应商文档审查</t></is></c>',
'      <c r="B5" t="inlineStr"><is><t>R</t></is></c>',
'      <c r="C5" t="inlineStr"><is><t>A</t></is></c>',
'      <c r="D5" t="inlineStr"><is><t>I</t></is></c>',
'      <c r="E5" t="inlineStr"><is><t></t></is></c>',
'      <c r="F5" t="inlineStr"><is><t>C</t></is></c>',
'      <c r="G5" t="inlineStr"><is><t></t></is></c>',
'    </row>',
'    <row r="6">',
'      <c r="A6" t="inlineStr"><is><t>数据收集与验证</t></is></c>',
'      <c r="B6" t="inlineStr"><is><t>R</t></is></c>',
'      <c r="C6" t="inlineStr"><is><t>C</t></is></c>',
'      <c r="D6" t="inlineStr"><is><t>A</t></is></c>',
'      <c r="E6" t="inlineStr"><is><t></t></is></c>',
'      <c r="F6" t="inlineStr"><is><t></t></is></c>',
'      <c r="G6" t="inlineStr"><is><t></t></is></c>',
'    </row>',
'    <row r="7">',
'      <c r="A7" t="inlineStr"><is><t>偏见检测模型开发</t></is></c>',
'      <c r="B7" t="inlineStr"><is><t>C</t></is></c>',
'      <c r="C7" t="inlineStr"><is><t>A</t></is></c>',
'      <c r="D7" t="inlineStr"><is><t>R</t></is></c>',
'      <c r="E7" t="inlineStr"><is><t></t></is></c>',
'      <c r="F7" t="inlineStr"><is><t></t></is></c>',
'      <c r="G7" t="inlineStr"><is><t>R</t></is></c>',
'    </row>',
'    <row r="8">',
'      <c r="A8" t="inlineStr"><is><t>统计分析</t></is></c>',
'      <c r="B8" t="inlineStr"><is><t>R</t></is></c>',
'      <c r="C8" t="inlineStr"><is><t>A</t></is></c>',
'      <c r="D8" t="inlineStr"><is><t></t></is></c>',
'      <c r="E8" t="inlineStr"><is><t></t></is></c>',
'      <c r="F8" t="inlineStr"><is><t></t></is></c>',
'      <c r="G8" t="inlineStr"><is><t>R</t></is></c>',
'    </row>',
'    <row r="9">',
'      <c r="A9" t="inlineStr"><is><t>风险评估</t></is></c>',
'      <c r="B9" t="inlineStr"><is><t>R</t></is></c>',
'      <c r="C9" t="inlineStr"><is><t>A</t></is></c>',
'      <c r="D9" t="inlineStr"><is><t></t></is></c>',
'      <c r="E9" t="inlineStr"><is><t></t></is></c>',
'      <c r="F9" t="inlineStr"><is><t></t></is></c>',
'      <c r="G9" t="inlineStr"><is><t>R</t></is></c>',
'    </row>',
'    <row r="10">',
'      <c r="A10" t="inlineStr"><is><t>改善计划制定</t></is></c>',
'      <c r="B10" t="inlineStr"><is><t>R</t></is></c>',
'      <c r="C10" t="inlineStr"><is><t>A</t></is></c>',
'      <c r="D10" t="inlineStr"><is><t></t></is></c>',
'      <c r="E10" t="inlineStr"><is><t>C</t></is></c>',
'      <c r="F10" t="inlineStr"><is><t></t></is></c>',
'      <c r="G10" t="inlineStr"><is><t></t></is></c>',
'    </row>',
'    <row r="11">',
'      <c r="A11" t="inlineStr"><is><t>成本估算</t></is></c>',
'      <c r="B11" t="inlineStr"><is><t>C</t></is></c>',
'      <c r="C11" t="inlineStr"><is><t></t></is></c>',
'      <c r="D11" t="inlineStr"><is><t></t></is></c>',
'      <c r="E11" t="inlineStr"><is><t>R</t></is></c>',
'      <c r="F11" t="inlineStr"><is><t></t></is></c>',
'      <c r="G11" t="inlineStr"><is><t></t></is></c>',
'    </row>',
'    <row r="12">',
'      <c r="A12" t="inlineStr"><is><t>改善措施实施</t></is></c>',
'      <c r="B12" t="inlineStr"><is><t>R</t></is></c>',
'      <c r="C12" t="inlineStr"><is><t>A</t></is></c>',
'      <c r="D12" t="inlineStr"><is><t>C</t></is></c>',
'      <c r="E12" t="inlineStr"><is><t></t></is></c>',
'      <c r="F12" t="inlineStr"><is><t></t></is></c>',
'      <c r="G12" t="inlineStr"><is><t></t></is></c>',
'    </row>',
'    <row r="13">',
'      <c r="A13" t="inlineStr"><is><t>实时监控</t></is></c>',
'      <c r="B13" t="inlineStr"><is><t>R</t></is></c>',
'      <c r="C13" t="inlineStr"><is><t>A</t></is></c>',
'      <c r="D13" t="inlineStr"><is><t>R</t></is></c>',
'      <c r="E13" t="inlineStr"><is><t></t></is></c>',
'      <c r="F13" t="inlineStr"><is><t></t></is></c>',
'      <c r="G13" t="inlineStr"><is><t></t></is></c>',
'    </row>',
'    <row r="14">',
'      <c r="A14" t="inlineStr"><is><t>报告编制</t></is></c>',
'      <c r="B14" t="inlineStr"><is><t>R</t></is></c>',
'      <c r="C14" t="inlineStr"><is><t>A</t></is></c>',
'      <c r="D14" t="inlineStr"><is><t></t></is></c>',
'      <c r="E14" t="inlineStr"><is><t></t></is></c>',
'      <c r="F14" t="inlineStr"><is><t></t></is></c>',
'      <c r="G14" t="inlineStr"><is><t>C</t></is></c>',
'    </row>',
'    <row r="15">',
'      <c r="A15" t="inlineStr"><is><t>合规审查</t></is></c>',
'      <c r="B15" t="inlineStr"><is><t>C</t></is></c>',
'      <c r="C15" t="inlineStr"><is><t>R</t></is></c>',
'      <c r="D15" t="inlineStr"><is><t></t></is></c>',
'      <c r="E15" t="inlineStr"><is><t></t></is></c>',
'      <c r="F15" t="inlineStr"><is><t>A</t></is></c>',
'      <c r="G15" t="inlineStr"><is><t></t></is></c>',
'    </row>',
'    <row r="16">',
'      <c r="A16" t="inlineStr"><is><t>政策更新</t></is></c>',
'      <c r="B16" t="inlineStr"><is><t>R</t></is></c>',
'      <c r="C16" t="inlineStr"><is><t>A</t></is></c>',
'      <c r="D16" t="inlineStr"><is><t></t></is></c>',
'      <c r="E16" t="inlineStr"><is><t></t></is></c>',
'      <c r="F16" t="inlineStr"><is><t>C</t></is></c>',
'      <c r="G16" t="inlineStr"><is><t></t></is></c>',
'    </row>',
'    <row r="17">',
'      <c r="A17" t="inlineStr"><is><t>培训组织</t></is></c>',
'      <c r="B17" t="inlineStr"><is><t>R</t></is></c>',
'      <c r="C17" t="inlineStr"><is><t>A</t></is></c>',
'      <c r="D17" t="inlineStr"><is><t></t></is></c>',
'      <c r="E17" t="inlineStr"><is><t></t></is></c>',
'      <c r="F17" t="inlineStr"><is><t></t></is></c>',
'      <c r="G17" t="inlineStr"><is><t>C</t></is></c>',
'    </row>',
'    <row r="18">',
'      <c r="A18" t="inlineStr"><is><t>文档归档</t></is></c>',
'      <c r="B18" t="inlineStr"><is><t>R</t></is></c>',
'      <c r="C18" t="inlineStr"><is><t>A</t></is></c>',
'      <c r="D18" t="inlineStr"><is><t></t></is></c>',
'      <c r="E18" t="inlineStr"><is><t></t></is></c>',
'      <c r="F18" t="inlineStr"><is><t></t></is></c>',
'      <c r="G18" t="inlineStr"><is><t></t></is></c>',
'    </row>',
'    <row r="19">',
'      <c r="A19" t="inlineStr"><is><t>下年度计划</t></is></c>',
'      <c r="B19" t="inlineStr"><is><t>R</t></is></c>',
'      <c r="C19" t="inlineStr"><is><t>A</t></is></c>',
'      <c r="D19" t="inlineStr"><is><t></t></is></c>',
'      <c r="E19" t="inlineStr"><is><t></t></is></c>',
'      <c r="F19" t="inlineStr"><is><t></t></is></c>',
'      <c r="G19" t="inlineStr"><is><t></t></is></c>',
'    </row>',
'  </sheetData>',
'  <pageMargins left="0.7" right="0.7" top="0.75" bottom="0.75" header="0.3" footer="0.3"/>',
'</worksheet>']

with open(os.path.join(BASE, "sheet6.xml"), 'w', encoding='utf-8') as f:
    f.write('\n'.join(s6))
print("Sheet 6 done")

# ===== SHEET 7: 预算规划 =====
s7 = ['<?xml version="1.0" encoding="UTF-8" standalone="yes"?>',
'<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">',
'  <sheetViews>',
'    <sheetView workbookViewId="0"/>',
'  </sheetViews>',
'  <sheetFormatPr defaultRowHeight="15" x14ac:dyDescent="0.25"',
'    xmlns:x14ac="http://schemas.microsoft.com/office/spreadsheetml/2009/9/ac"/>',
'  <cols>',
'    <col min="1" max="1" width="22" customWidth="1"/>',
'    <col min="2" max="2" width="14" customWidth="1"/>',
'    <col min="3" max="3" width="14" customWidth="1"/>',
'    <col min="4" max="4" width="14" customWidth="1"/>',
'    <col min="5" max="5" width="14" customWidth="1"/>',
'    <col min="6" max="6" width="16" customWidth="1"/>',
'  </cols>',
'  <sheetData>',
'    <row r="1">',
'      <c r="A1" t="inlineStr"><is><t>预算规划</t></is></c>',
'    </row>',
'    <row r="2">',
'      <c r="A2" t="inlineStr"><is><t>算法审计与薪酬偏见治理 - 2026年度预算</t></is></c>',
'    </row>',
'    <row r="4">',
'      <c r="A4" t="inlineStr"><is><t>费用类别</t></is></c>',
'      <c r="B4" t="inlineStr"><is><t>Q1</t></is></c>',
'      <c r="C4" t="inlineStr"><is><t>Q2</t></is></c>',
'      <c r="D4" t="inlineStr"><is><t>Q3</t></is></c>',
'      <c r="E4" t="inlineStr"><is><t>Q4</t></is></c>',
'      <c r="F4" t="inlineStr"><is><t>年度合计</t></is></c>',
'    </row>',
'    <row r="5">',
'      <c r="A5" t="inlineStr"><is><t>人员成本</t></is></c>',
'      <c r="B5" s="5"><v>50000</v></c>',
'      <c r="C5" s="5"><v>50000</v></c>',
'      <c r="D5" s="5"><v>50000</v></c>',
'      <c r="E5" s="5"><v>50000</v></c>',
'      <c r="F5" s="6"><f>SUM(B5:E5)</f><v></v></c>',
'    </row>',
'    <row r="6">',
'      <c r="A6" t="inlineStr"><is><t>外部顾问费用</t></is></c>',
'      <c r="B6" s="5"><v>80000</v></c>',
'      <c r="C6" s="5"><v>60000</v></c>',
'      <c r="D6" s="5"><v>40000</v></c>',
'      <c r="E6" s="5"><v>30000</v></c>',
'      <c r="F6" s="6"><f>SUM(B6:E6)</f><v></v></c>',
'    </row>',
'    <row r="7">',
'      <c r="A7" t="inlineStr"><is><t>技术工具</t></is></c>',
'      <c r="B7" s="5"><v>20000</v></c>',
'      <c r="C7" s="5"><v>10000</v></c>',
'      <c r="D7" s="5"><v>5000</v></c>',
'      <c r="E7" s="5"><v>5000</v></c>',
'      <c r="F7" s="6"><f>SUM(B7:E7)</f><v></v></c>',
'    </row>',
'    <row r="8">',
'      <c r="A8" t="inlineStr"><is><t>培训费用</t></is></c>',
'      <c r="B8" s="5"><v>0</v></c>',
'      <c r="C8" s="5"><v>15000</v></c>',
'      <c r="D8" s="5"><v>15000</v></c>',
'      <c r="E8" s="5"><v>0</v></c>',
'      <c r="F8" s="6"><f>SUM(B8:E8)</f><v></v></c>',
'    </row>',
'    <row r="9">',
'      <c r="A9" t="inlineStr"><is><t>差旅费用</t></is></c>',
'      <c r="B9" s="5"><v>5000</v></c>',
'      <c r="C9" s="5"><v>5000</v></c>',
'      <c r="D9" s="5"><v>3000</v></c>',
'      <c r="E9" s="5"><v>2000</v></c>',
'      <c r="F9" s="6"><f>SUM(B9:E9)</f><v></v></c>',
'    </row>',
'    <row r="10">',
'      <c r="A10" t="inlineStr"><is><t>应急储备</t></is></c>',
'      <c r="B10" s="5"><v>10000</v></c>',
'      <c r="C10" s="5"><v>10000</v></c>',
'      <c r="D10" s="5"><v>10000</v></c>',
'      <c r="E10" s="5"><v>10000</v></c>',
'      <c r="F10" s="6"><f>SUM(B10:E10)</f><v></v></c>',
'    </row>',
'    <row r="11">',
'      <c r="A11" t="inlineStr"><is><t>合计</t></is></c>',
'      <c r="B11" s="6"><f>SUM(B5:B10)</f><v></v></c>',
'      <c r="C11" s="6"><f>SUM(C5:C10)</f><v></v></c>',
'      <c r="D11" s="6"><f>SUM(D5:D10)</f><v></v></c>',
'      <c r="E11" s="6"><f>SUM(E5:E10)</f><v></v></c>',
'      <c r="F11" s="6"><f>SUM(B11:E11)</f><v></v></c>',
'    </row>',
'    <row r="13">',
'      <c r="A13" t="inlineStr"><is><t>预算说明</t></is></c>',
'    </row>',
'    <row r="14">',
'      <c r="A14" t="inlineStr"><is><t>人员成本</t></is></c>',
'      <c r="B14" t="inlineStr"><is><t>HR团队参与审计工作的时间成本，按季度分摊</t></is></c>',
'    </row>',
'    <row r="15">',
'      <c r="A15" t="inlineStr"><is><t>外部顾问费用</t></is></c>',
'      <c r="B15" t="inlineStr"><is><t>外部审计师和专业顾问费用，集中在前期</t></is></c>',
'    </row>',
'    <row r="16">',
'      <c r="A16" t="inlineStr"><is><t>技术工具</t></is></c>',
'      <c r="B16" t="inlineStr"><is><t>数据分析工具、监控系统等软件授权费用</t></is></c>',
'    </row>',
'    <row r="17">',
'      <c r="A17" t="inlineStr"><is><t>培训费用</t></is></c>',
'      <c r="B17" t="inlineStr"><is><t>算法公平性培训课程和材料费用</t></is></c>',
'    </row>',
'    <row r="18">',
'      <c r="A18" t="inlineStr"><is><t>应急储备</t></is></c>',
'      <c r="B18" t="inlineStr"><is><t>用于应对未预见的审计发现所需的额外工作</t></is></c>',
'    </row>',
'  </sheetData>',
'  <pageMargins left="0.7" right="0.7" top="0.75" bottom="0.75" header="0.3" footer="0.3"/>',
'</worksheet>']

with open(os.path.join(BASE, "sheet7.xml"), 'w', encoding='utf-8') as f:
    f.write('\n'.join(s7))
print("Sheet 7 done")
print("All sheets for workbook 2 complete!")



