# -*- coding: utf-8 -*-
"""Append P21-P130 with simpler, valid content.

This script appends valid Python source code to gen_pptx_part2.py for
pages 21-130. Content is simplified to avoid quoting issues.
"""
import os

# Append header section for P14-P20 already exists
# Now append P21-P130
# Use a content template approach - each page is generated by a small
# helper that uses safe strings (no embedded quotes)

CODE = []

# ============== 2.2 4R 循环总览 ==============
def add_P21():
    CODE.append('''
def P21():
    s = prs.slides.add_slide(BLANK); bg(s)
    hdr(s, 21, "第二章 · 流程规划", "2.2 · 4R 循环总览")
    tx(s, Inches(0.6), Inches(1.3), Inches(12.1), Inches(0.4), "4R 循环 · 工作坊质量框架", sz=18, c=DARK, b=True)
    rs = [
        ("R1", "回顾", "Recall", "10-15%", "重新激活学员记忆", RED),
        ("R2", "现实", "Reality", "25-30%", "学员真实工作情境", GREEN),
        ("R3", "共创", "Reimagine", "30-35%", "群体智慧共创方案", GOLD),
        ("R4", "行动", "Resolve", "25-30%", "具体实践承诺", DARK),
    ]
    for i, (code_n, t, en, pct, desc, c) in enumerate(rs):
        x = Inches(0.6 + i * 3.1)
        rc(s, x, Inches(2.0), Inches(2.9), Inches(4.5), WHT, line=LGT)
        rc(s, x, Inches(2.0), Inches(2.9), Inches(0.8), c)
        tx(s, x, Inches(2.0), Inches(2.9), Inches(0.8), code_n, sz=36, c=WHT, b=True, al=PP_ALIGN.CENTER, an=MSO_ANCHOR.MIDDLE)
        tx(s, x + Inches(0.2), Inches(3.0), Inches(2.5), Inches(0.5), t, sz=22, c=DARK, b=True)
        tx(s, x + Inches(0.2), Inches(3.5), Inches(2.5), Inches(0.4), en, sz=12, c=GRY)
        tx(s, x + Inches(0.2), Inches(4.0), Inches(2.5), Inches(0.5), pct, sz=18, c=c, b=True)
        tx(s, x + Inches(0.2), Inches(4.7), Inches(2.5), Inches(0.8), desc, sz=11, c=TXT)
    ftr(s)
    note(s, "【2.2 4R 循环总览】4R 是工作坊质量框架。R1 回顾、 R2 现实、 R3 共创、 R4 行动。R1 占 10-15%，R2 占 25-30%，R3 占 30-35%，R4 占 25-30%。顺序固定，但每个 R 的时间占比根据内容属性调整。")
''')

# Many more pages - using a compact generator pattern
def add_pages_compact():
    """Add pages 22-130 in compact form."""

    # Page 22: R1 details
    CODE.append('''
def P22():
    s = prs.slides.add_slide(BLANK); bg(s)
    hdr(s, 22, "第二章 · 流程规划", "2.2 · R1 回顾 · Recall")
    rc(s, Inches(0.6), Inches(1.3), Inches(12.1), Inches(0.4), RED)
    tx(s, Inches(0.8), Inches(1.4), Inches(11.7), Inches(0.3), "R1 回顾 · 关键：重新激活学员记忆", sz=18, c=WHT, b=True)
    rc(s, Inches(0.6), Inches(2.0), Inches(6.0), Inches(5.0), WHT, line=LGT)
    rc(s, Inches(0.6), Inches(2.0), Inches(6.0), Inches(0.5), RED)
    tx(s, Inches(0.8), Inches(2.0), Inches(5.6), Inches(0.5), "R1 的 3 个核心问题", sz=14, c=WHT, b=True, an=MSO_ANCHOR.MIDDLE)
    qs = ["您现在还记得上次课的哪些内容？", "上次课哪个点对您印象最深？", "上次课后您做了什么？"]
    for i, q in enumerate(qs):
        y = Inches(2.7 + i * 1.3)
        rc(s, Inches(0.8), y, Inches(5.6), Inches(1.1), LBG, line=LGT)
        tx(s, Inches(1.0), y + Inches(0.2), Inches(0.5), Inches(0.5), f"Q{i+1}", sz=18, c=RED, b=True)
        tx(s, Inches(1.7), y + Inches(0.2), Inches(4.5), Inches(0.8), q, sz=12, c=TXT)
    rc(s, Inches(6.8), Inches(2.0), Inches(5.9), Inches(5.0), WHT, line=LGT)
    rc(s, Inches(6.8), Inches(2.0), Inches(5.9), Inches(0.5), DARK)
    tx(s, Inches(7.0), Inches(2.0), Inches(5.5), Inches(0.5), "R1 常见错误", sz=14, c=WHT, b=True, an=MSO_ANCHOR.MIDDLE)
    errs = ["讲师单方面回顾，学员沉默", "回顾时间超过 30 分钟", "回顾内容跟今天的工作坊无关", "回顾是知识点的复述，没有激活"]
    for i, e in enumerate(errs):
        y = Inches(2.7 + i * 1.0)
        tx(s, Inches(7.0), y, Inches(5.5), Inches(0.9), f"x {e}", sz=12, c=RED)
    ftr(s)
    note(s, "【2.2 R1 回顾】R1 关键：重新激活学员记忆。3 个核心问题。常见错误：讲师单方面回顾 / 时间超 30 分钟 / 内容跟工作坊无关 / 是知识点复述没激活。")
''')

# Helper for adding R2/R3/R4 detail pages
def add_R_detail(num, name, en, color, qs, errs, focus):
    CODE.append(f'''
def P{num}():
    s = prs.slides.add_slide(BLANK); bg(s)
    hdr(s, {num}, "第二章 · 流程规划", "2.2 · {name} · {en}")
    rc(s, Inches(0.6), Inches(1.3), Inches(12.1), Inches(0.4), {color})
    tx(s, Inches(0.8), Inches(1.4), Inches(11.7), Inches(0.3), "{name} · 关键：{focus}", sz=18, c=WHT, b=True)
    rc(s, Inches(0.6), Inches(2.0), Inches(6.0), Inches(5.0), WHT, line=LGT)
    rc(s, Inches(0.6), Inches(2.0), Inches(6.0), Inches(0.5), {color})
    tx(s, Inches(0.8), Inches(2.0), Inches(5.6), Inches(0.5), "{name} 的核心问题", sz=14, c=WHT, b=True, an=MSO_ANCHOR.MIDDLE)''')
    for i, q in enumerate(qs):
        CODE.append(f'''    rc(s, Inches(0.8), Inches({2.7 + i*1.3}), Inches(5.6), Inches(1.1), LBG, line=LGT)
    tx(s, Inches(1.0), Inches({2.9 + i*1.3}), Inches(0.5), Inches(0.5), f"Q{i+1}", sz=18, c={color}, b=True)
    tx(s, Inches(1.7), Inches({2.9 + i*1.3}), Inches(4.5), Inches(0.8), "{q}", sz=12, c=TXT)''')
    CODE.append(f'''    rc(s, Inches(6.8), Inches(2.0), Inches(5.9), Inches(5.0), WHT, line=LGT)
    rc(s, Inches(6.8), Inches(2.0), Inches(5.9), Inches(0.5), DARK)
    tx(s, Inches(7.0), Inches(2.0), Inches(5.5), Inches(0.5), "{name} 常见错误", sz=14, c=WHT, b=True, an=MSO_ANCHOR.MIDDLE)''')
    for i, e in enumerate(errs):
        CODE.append(f'''    tx(s, Inches(7.0), Inches({2.7 + i*1.0}), Inches(5.5), Inches(0.9), f"x {e}", sz=12, c=RED)''')
    CODE.append('''    ftr(s)
    note(s, \"""")''' + f'【2.2 {name}】{focus}。常见错误：' + ' / '.join(errs) + '。' + '''""")
''')

# We'll use direct f-string for simpler pages
# This is getting complex. Let me just write all 109 pages directly.

# Actually, let me just use a much simpler pattern - one function per page
# with a consistent template

# R1 - P22
# R2 - P23, P24
# R3 - P25, P26
# R4 - P27, P28
# 2.3 不同内容属性 - P29, P30
# 2.4 Activity 2A - P31, P32
# ============== 第三章 点燃参与 ==============
# 3.1 开场 - P33-P39
# 3.2 暖场 - P40-P44
# 3.3 营造安全感 - P45-P48
# 3.4 收心 - P49-P52
# 3.5 开场常见错误 - P53-P56
# 3.6 Activity 3A - P57-P60
# 3.7 小结 - P61
# ============== 第四章 深问与共创 ==============
# 4.1 好问题 vs 坏问题 - P62-P67
# 4.2 4 类提问 - P68-P73
# 4.3 学员中心 - P74-P77
# 4.4 翻转 - P78-P82
# 4.5 共创 - P83-P88
# 4.6 Activity 4A - P89-P92
# 4.7 小结 - P93
# ============== 第五章 训后跟进 ==============
# 5.1 跟进四法 - P94-P98
# 5.2 30 天实施 - P99-P104
# 5.3 学员互助 - P105-P108
# 5.4 Activity 5A - P109-P112
# 5.5 长期主义 - P113-P116
# 5.6 总结 - P117-P130

# Given the complexity, let me just use a single large function
# that generates all 109 pages
print("Stub - will be replaced with full generator")
