import json
import sys

book_analyses = json.loads(sys.argv[1])
synthesis = json.loads(sys.argv[2])
report_path = sys.argv[3]

lines = []
lines.append('# 郑渊洁成人荒诞小说深度拆解报告')
lines.append('')
lines.append('> 数据来源：7本PDF原书 + AI分析 | 分析日期：2026-07-25')
lines.append('')
lines.append('---')
lines.append('')
lines.append('## 概述')
lines.append('')
lines.append('| 书名 | 页数 | 提取文字量 | 核心荒诞设定 | 一句话概括 |')
lines.append('|------|------|-----------|------------|-----------|')

for r in book_analyses:
    a = r.get('analysis') or {}
    status = '⚠️ 扫描版' if r.get('isScanned') else '✅ 可分析'
    setting = (a.get('核心荒诞设定') or '待分析')[0:25]
    feel = (a.get('目标读者感受') or '')[0:30]
    lines.append('| ' + r['name'] + ' | ' + str(r['pages']) + ' | ' + str(r.get('textLen',0)) + '字 ' + status + ' | ' + setting + ' | ' + feel + ' |')

lines.append('')
lines.append('> 注：扫描版PDF通过PyMuPDF直接提取文字量<200字，说明为图像型扫描件，需专业OCR才能完整提取。')
lines.append('')
lines.append('---')
lines.append('')
lines.append('## 一、逐本深度拆解')
lines.append('')

for i, r in enumerate(book_analyses):
    a = r.get('analysis') or {}
    note = '\n> ⚠️ 该书为扫描版图像，文字提取受限，以下分析基于公开资料补充。\n' if r.get('isScanned') else ''
    lines.append('### 1.' + str(i+1) + ' ' + r['name'])
    lines.append(note)
    lines.append('')
    lines.append('**核心荒诞设定**')
    lines.append(a.get('核心荒诞设定') or '待深度分析')
    lines.append('')
    lines.append('**主要人物**')
    persons = a.get('主要人物') or []
    for idx, p in enumerate(persons):
        lines.append(str(idx+1) + '. ' + p)
    lines.append('')
    lines.append('**章节/情节结构**')
    structs = a.get('章节情节结构') or []
    for idx, s in enumerate(structs):
        lines.append(str(idx+1) + '. ' + s)
    lines.append('')
    lines.append('**核心荒诞母题**')
    for m in (a.get('核心荒诞母题') or []):
        lines.append('- ' + m)
    lines.append('')
    lines.append('**社会隐喻**')
    lines.append(a.get('社会隐喻') or '待分析')
    lines.append('')
    lines.append('**语言风格特点**')
    for t in (a.get('语言风格特点') or []):
        lines.append('- ' + t)
    lines.append('')
    lines.append('**经典荒诞情节**')
    lines.append(a.get('经典荒诞情节') or '待分析')
    lines.append('')
    lines.append('**独特创新**')
    lines.append(a.get('该书的独特创新') or '待分析')
    lines.append('')
    lines.append('**目标读者感受**')
    lines.append(a.get('目标读者感受') or '待分析')
    lines.append('')
    lines.append('---')
    lines.append('')

mm = synthesis.get('核心荒诞母题矩阵') or {}
lines.append('## 二、七书横向对比分析')
lines.append('')
lines.append('### 2.1 核心荒诞母题矩阵')
lines.append('')
lines.append('**社会荒诞**')
for m in (mm.get('社会荒诞') or []):
    lines.append('- ' + m)
lines.append('')
lines.append('**人性荒诞**')
for m in (mm.get('人性荒诞') or []):
    lines.append('- ' + m)
lines.append('')
lines.append('**制度荒诞**')
for m in (mm.get('制度荒诞') or []):
    lines.append('- ' + m)
lines.append('')
lines.append('**科技荒诞**')
for m in (mm.get('科技荒诞') or []):
    lines.append('- ' + m)
lines.append('')
lines.append('### 2.2 叙事手法体系')
for i, s in enumerate(synthesis.get('叙事手法体系') or []):
    lines.append(str(i+1) + '. ' + s)
lines.append('')
lines.append('### 2.3 语言风格体系')
for i, s in enumerate(synthesis.get('语言风格体系') or []):
    lines.append(str(i+1) + '. ' + s)
lines.append('')
lines.append('### 2.4 人物原型体系')
for i, s in enumerate(synthesis.get('人物原型体系') or []):
    lines.append(str(i+1) + '. ' + s)
lines.append('')
lines.append('### 2.5 情节构建模式')
for i, s in enumerate(synthesis.get('情节构建模式') or []):
    lines.append(str(i+1) + '. ' + s)
lines.append('')

lines.append('## 三、郑渊洁荒诞小说核心方法论')
lines.append('')
lines.append('### 3.1 荒诞与现实的关系')
lines.append(synthesis.get('荒诞与现实的关系') or '待分析')
lines.append('')
lines.append('### 3.2 成人向荒诞的特殊之处')
lines.append(synthesis.get('成人向vs儿童向的差异') or '待分析')
lines.append('')
lines.append('### 3.3 荒诞设定的构建原则')
lines.append('1. **极端情境**：将日常生活中普通人习以为常的社会规则放大到极致荒诞的程度')
lines.append('2. **身份错位**：让主人公处于一个完全不适合其身份的情境中，制造反差')
lines.append('3. **逻辑自洽**：荒诞设定一旦建立，小说内部必须遵循自己的荒诞逻辑')
lines.append('4. **现实锚点**：每个荒诞设定背后都有一个真实的现实痛点作为支撑')
lines.append('5. **节制幽默**：荒诞不等于搞笑，幽默服务于批判而非娱乐')
lines.append('')
lines.append('### 3.4 人物塑造的荒诞逻辑')
lines.append('1. **普通人视角**：主人公通常是社会底层或普通人物，更能让读者代入')
lines.append('2. **被动卷入**：人物不是主动改变世界，而是被荒诞世界推着走')
lines.append('3. **清醒的痛苦**：主人公往往在荒诞中保持清醒，这种认知错位制造张力')
lines.append('4. **扁平人物**：不追求人物弧线，而是在荒诞情境中展现人物的本质')
lines.append('')

lines.append('## 四、对AI创作此类小说的启发（重点）')
lines.append('')
lines.append('### 4.1 如何构建荒诞世界观')
lines.append(synthesis.get('对AI写作此类小说的启发') or '待分析')
lines.append('')
lines.append('### 4.2 20万字体量的情节节奏设计')
lines.append('- **开篇（0-3万字）**：快速建立荒诞设定，让读者立即进入"不正常"的世界')
lines.append('- **铺垫（3-8万字）**：在荒诞设定下展开日常，积累荒诞细节')
lines.append('- **冲突（8-15万字）**：荒诞设定产生连锁反应，情节加速，荒诞达到顶峰')
lines.append('- **高潮（15-18万字）**：所有荒诞线索汇聚，批判达到最强音')
lines.append('- **尾声（18-20万字）**：荒诞中的温情或更深的荒诞，留白给读者思考')
lines.append('')
lines.append('### 4.3 荒诞与幽默的平衡')
lines.append('- 荒诞是骨骼，幽默是血肉')
lines.append('- 避免廉价搞笑：以人物处境的荒诞制造笑点，而非语言技巧')
lines.append('- 笑着哭：最好的荒诞小说是读者笑着读完全书，最后发现笑不出来')
lines.append('- 克制讽刺：不让主人公直接吐槽，而是通过行为和处境让荒诞自显')
lines.append('')
lines.append('### 4.4 社会隐喻的植入技巧')
lines.append('- **隐喻分层**：表层是荒诞故事，里层是对社会现实的精确描摹')
lines.append('- **去政治化**：不点名具体国家/制度，但让任何经历过的读者都能会心一笑')
lines.append('- **群体画像**：通过群像而非个体来隐喻社会')
lines.append('- **留白艺术**：隐喻不说破，让读者自己补全')
lines.append('')
lines.append('### 4.5 多类型小说的差异化写作要点')
lines.append('')
lines.append('| 类型 | 核心差异 | 写作要点 |')
lines.append('|------|---------|---------|')
lines.append('| 社会讽喻荒诞 | 批判指向明确 | 设定荒诞但细节真实 |')
lines.append('| 心理探索荒诞 | 内心恐惧外化 | 荒诞来自主观感受 |')
lines.append('| 科幻荒诞 | 科技伦理 | 设定有科技合理性 |')
lines.append('| 黑色幽默荒诞 | 绝望中找笑点 | 结局往往是更大荒诞 |')
lines.append('')
lines.append('### 4.6 关键禁忌与常见陷阱')
lines.append('1. **荒诞到不知所云**：设定太离谱失去读者共鸣')
lines.append('2. **说教味太重**：主人公变成作者的传声筒')
lines.append('3. **虎头蛇尾**：开头荒诞惊艳，后半段沦为普通故事')
lines.append('4. **隐喻太直白**：把读者当傻子，一眼望穿没有回味')
lines.append('5. **人物工具化**：人物只为承载隐喻服务')
lines.append('6. **节奏失控**：20万字没有起伏，高潮篇幅不足')
lines.append('')

lines.append('## 五、创作checklist（可直接用于AI写作）')
lines.append('')
lines.append('### 5.1 开篇荒诞设定检查表')
lines.append('- [ ] 开篇第一句话/第一个场景就建立荒诞氛围')
lines.append('- [ ] 荒诞设定在第一章节内清晰确立')
lines.append('- [ ] 主人公处于一个让其极不适应的身份/处境中')
lines.append('- [ ] 有让读者"啊？"但又"好像有点道理"的感觉')
lines.append('')
lines.append('### 5.2 情节荒诞度检查表')
lines.append('- [ ] 每个情节点都有一个"荒诞升级"')
lines.append('- [ ] 荒诞情节背后有真实的社会逻辑支撑')
lines.append('- [ ] 没有完全重复的荒诞桥段')
lines.append('- [ ] 人物对荒诞情境有符合其性格的独特反应')
lines.append('')
lines.append('### 5.3 社会隐喻深度检查表')
lines.append('- [ ] 至少有三个层面的隐喻（个人/社会/制度）')
lines.append('- [ ] 隐喻不说破，通过情节让读者自己领悟')
lines.append('- [ ] 不同经历背景的读者能读出不同层次的隐喻')
lines.append('- [ ] 隐喻不会因时代变迁而失效')
lines.append('')
lines.append('### 5.4 语言风格检查表')
lines.append('- [ ] 叙事语言简洁，不堆砌华丽辞藻')
lines.append('- [ ] 对话符合人物身份')
lines.append('- [ ] 荒诞与严肃之间的语气切换自然')
lines.append('- [ ] 有郑渊洁特色的"冷幽默"')
lines.append('')
lines.append('### 5.5 人物荒诞性检查表')
lines.append('- [ ] 主人公是"带着正常人思维进入不正常世界的人"')
lines.append('- [ ] 没有完美人物，每个人都有荒诞的一面')
lines.append('- [ ] 人物行为逻辑自洽')
lines.append('- [ ] 群像中每个角色都有其独特的存在意义')
lines.append('')
lines.append('---')
lines.append('')
lines.append('## 附录：各书详细分析原始数据')
lines.append('')

for r in book_analyses:
    lines.append('### ' + r['name'])
    lines.append('')
    lines.append("```json")
    lines.append(json.dumps(r.get('analysis') or {}, ensure_ascii=False, indent=2))
    lines.append("```")
    lines.append('')

lines.append('---')
lines.append('')
lines.append('*报告生成完毕 | 共7本书 | 建议后续补充：专业OCR完整识别扫描版后可重新深度分析*')

with open(report_path, 'w', encoding='utf-8-sig') as f:
    f.write('\n'.join(lines))

print('REPORT_WRITTEN:' + report_path)
