using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Wordprocessing;
using System.Text;

string outputPath = @"D:\2026年课程\竞越\释潜：UYLP释放你的领导潜能\完整课程包\05_讲师手册\UYLP_讲师手册_完整版.docx";
Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);

// Use memory stream to avoid file locking issues
using var ms = new MemoryStream();
using (var doc = WordprocessingDocument.Create(ms, WordprocessingDocumentType.Document, true))
{
    var mainPart = doc.AddMainDocumentPart();
    mainPart.Document = new Document();
    var body = new Body();
    mainPart.Document.Body = body;

    // Helper to add paragraph
    void AddP(string text, int? size = null, bool bold = false, int? color = null, bool hasBg = false)
    {
        var p = new Paragraph();
        var run = new Run();
        var props = new RunProperties();

        if (bold) props.Append(new Bold());
        if (size.HasValue)
        {
            var sz = new FontSize { Val = (size.Value * 2).ToString() };
            props.Append(sz);
        }
        if (color.HasValue)
        {
            var clr = new Color { Val = color.Value.ToString("X6") };
            props.Append(clr);
        }
        run.Append(props);
        run.Append(new Text(text) { Space = SpaceProcessingModeValues.Preserve });
        p.Append(run);
        body.Append(p);
    }

    void AddH1(string text) => AddP(text, 28, true, 0xFFFFFF, true);
    void AddH2(string text) => AddP(text, 24, true, 0xFFFFFF, true);
    void AddH3(string text) => AddP(text, 16, true, 0x1F497D);
    void AddH4(string text) => AddP(text, 14, true, 0x1F497D);
    void AddNormal(string text) => AddP(text, 12);

    void AddBreak()
    {
        body.Append(new Paragraph(new Run(new Break())));
    }

    // Title page
    AddP("UYLP", 36, true);
    AddP("释放你的领导潜能", 28, true);
    AddP("—— 讲师手册 ——", 24, true);
    AddBreak();
    AddP("Unleash Your Leadership Potential", 18, true);
    AddBreak();
    AddP("课程定位：企业中高层管理者领导力发展", 12, false, 0x7D5151);
    AddP("标准课时：2天（每天6小时，共12小时）", 12, false, 0x7D5151);
    AddP("学员人数：24-32人（建议分组，每组4-8人）", 12, false, 0x7D5151);
    AddBreak();
    AddP("版本：完整版 v1.0", 12);
    AddP("发布日期：2026年6月", 12);
    AddBreak();

    // TOC
    AddP("目 录", 28, true, 0xFFFFFF);
    AddP("第一部分：讲师指南", 14, true, 0x1F497D);
    AddP("  1.1 课程定位与核心价值", 12);
    AddP("  1.2 讲师角色定位", 12);
    AddP("  1.3 课程设计理念", 12);
    AddP("  1.4 教学方法论", 12);
    AddBreak();
    AddP("第二部分：完整授课指引", 14, true, 0x1F497D);
    AddP("  2.1 模块一：领导者角色与绩效管理体系", 12);
    AddP("  2.2 模块二：辅导入门：WHEN/HOW/Y", 12);
    AddP("  2.3 模块三：有效反馈：CAIR模型", 12);
    AddP("  2.4 模块四：困难谈话", 12);
    AddP("  2.5 模块五：联结沟通与工作关系", 12);
    AddP("  2.6 模块六：高级辅导、有效授权与MAP", 12);
    AddBreak();
    AddP("第三部分：体验活动完整设计", 14, true, 0x1F497D);
    AddP("  3.1 月球会议（第一模块）", 12);
    AddP("  3.2 三岛救援（第五模块）", 12);
    AddBreak();
    AddP("第四部分：角色扮演完整设计", 14, true, 0x1F497D);
    AddP("  4.1 辅导对话角色扮演", 12);
    AddP("  4.2 反馈对话角色扮演", 12);
    AddP("  4.3 困难谈话角色扮演", 12);
    AddBreak();
    AddP("第五部分：讲师工具", 14, true, 0x1F497D);
    AddP("  5.1 讲师时间控制表", 12);
    AddP("  5.2 学员表现观察量表", 12);
    AddP("  5.3 课程评估指引", 12);
    AddP("  5.4 危机处理预案", 12);
    AddBreak();
    AddP("第六部分：附录", 14, true, 0x1F497D);
    AddP("  6.1 核心模型速查", 12);
    AddP("  6.2 参考资料", 12);
    AddP("  6.3 术语表", 12);
    AddBreak();

    // Part 1
    AddH1("第一部分：讲师指南");
    AddH2("1.1 课程定位与核心价值");
    AddNormal("UYLP（Unleash Your Leadership Potential）是一款专注于帮助企业中高层管理者释放领导潜能的体验式课程。");
    AddBreak();
    AddH3("核心价值主张");
    AddNormal("1. 从\"管人理事\"到\"理人管事\"：帮助管理者从繁琐的事务中抽身，通过有效的辅导、反馈和授权提升团队整体绩效。");
    AddNormal("2. 从\"被动应对\"到\"主动干预\"：教授管理者在关键时刻进行有效干预的技能，而不是等问题恶化。");
    AddNormal("3. 从\"个人英雄\"到\"教练型领导\"：培养管理者的\"乘法思维\"——通过培养他人成就更大的事业。");
    AddBreak();
    AddH3("学员收益");
    AddNormal("• 掌握辅导、反馈、授权三大核心干预技能");
    AddNormal("• 提升困难谈话的处理能力");
    AddNormal("• 建立更加稳固的工作关系和团队联结");
    AddNormal("• 学会使用MAP模型进行高级辅导和授权");
    AddBreak();

    AddH2("1.2 讲师角色定位");
    AddNormal("UYLP讲师不仅是知识的传递者，更是学习的促进者和体验的引导者。");
    AddBreak();
    AddH3("三重角色");
    AddH4("【角色一：学习设计师】");
    AddNormal("• 精心设计每一个学习环节，确保体验与反思的平衡");
    AddNormal("• 将抽象的领导力概念转化为可操作的行为技能");
    AddNormal("• 构建安全的学习环境，让学员敢于尝试和犯错");
    AddBreak();
    AddH4("【角色二：引导师】");
    AddNormal("• 通过提问而非告知来激发学员思考");
    AddNormal("• 鼓励学员分享经验，促进相互学习");
    AddNormal("• 在关键时刻提供\"战略性暂停\"，让学员消化体验");
    AddBreak();
    AddH4("【角色三：教练】");
    AddNormal("• 示范而非说教——用自身经验诠释概念");
    AddNormal("• 给予及时、正向的反馈，强化正确行为");
    AddNormal("• 保持中立，不将自己的价值观强加于学员");
    AddBreak();

    AddH2("1.3 课程设计理念");
    AddH3("体验式学习循环");
    AddNormal("本课程采用大卫·科尔布（David Kolb）的体验式学习循环作为核心教学设计理念：");
    AddNormal("具体经验 → 反思观察 → 抽象概念化 → 主动实践");
    AddNormal("每一个模块都遵循这一循环：先通过活动或案例让学员获得\"切身体验\"，然后引导他们\"反思观察\"，接着帮助他们\"抽象概念化\"形成理论框架，最后设计练习让学员\"主动实践\"。");
    AddBreak();
    AddH3("3:1参与原则");
    AddNormal("根据成人学习理论，成人最佳学习效果来自于3:1的参与比例：");
    AddNormal("• 30% 时间用于知识输入（讲解、阅读、观看）");
    AddNormal("• 70% 时间用于体验和练习（活动、讨论、角色扮演、反馈）");
    AddNormal("本课程严格遵循这一原则，确保学员有充足的动手操作机会。");
    AddBreak();

    AddH2("1.4 教学方法论");
    AddH3("核心教学方法");
    AddH4("【体验式活动】");
    AddNormal("• 月球会议：体验领导者在资源受限情况下的决策困境");
    AddNormal("• 三岛救援：理解联结沟通的重要性和团队协作的复杂性");
    AddBreak();
    AddH4("【角色扮演】");
    AddNormal("• 辅导对话：练习WHEN/HOW/Y模型的实际应用");
    AddNormal("• 反馈对话：运用CAIR模型进行有效反馈");
    AddNormal("• 困难谈话：处理敏感话题的沟通技巧");
    AddBreak();
    AddH4("【小组讨论】");
    AddNormal("• 反思问题：连接体验与日常工作场景");
    AddNormal("• 经验分享：促进学员间的相互学习");
    AddBreak();
    AddH3("关键教学原则");
    AddNormal("1. 安全感优先：创造一个让学员敢于冒险、坦诚分享的环境");
    AddNormal("2. 提问优于告知：通过苏格拉底式提问引导学员自己得出结论");
    AddNormal("3. 错误是学习机会：将错误转化为建设性的学习时刻");
    AddNormal("4. 联系实际：确保每一个概念都能连接到学员的实际工作场景");
    AddBreak();

    // Part 2
    AddH1("第二部分：完整授课指引");
    AddH2("课程时间总览");
    AddH3("【Day 1 时间表】");
    AddNormal("08:30-09:00 | 签到与准备 | 学员签到，发放材料");
    AddNormal("09:00-09:15 | 开场 | 课程介绍，目标设定");
    AddNormal("09:15-10:45 | 模块一 | 领导者角色与绩效管理体系");
    AddNormal("10:45-11:00 | 茶歇");
    AddNormal("11:00-12:30 | 模块二（上）| 辅导入门：WHEN/HOW/Y");
    AddNormal("12:30-13:30 | 午餐");
    AddNormal("13:30-15:30 | 模块二（下）| 辅导入门：角色扮演练习");
    AddNormal("15:30-15:45 | 茶歇");
    AddNormal("15:45-17:15 | 模块三 | 有效反馈：CAIR模型");
    AddNormal("17:15-17:30 | 总结 | 当日回顾，明日预告");
    AddBreak();
    AddH3("【Day 2 时间表】");
    AddNormal("08:30-09:00 | 签到与回顾 | 回答学员问题，回顾昨日内容");
    AddNormal("09:00-10:30 | 模块四 | 困难谈话");
    AddNormal("10:30-10:45 | 茶歇");
    AddNormal("10:45-12:15 | 模块五（上）| 联结沟通与工作关系");
    AddNormal("12:15-13:15 | 午餐");
    AddNormal("13:15-15:15 | 模块五（下）| 三岛救援体验活动");
    AddNormal("15:15-15:30 | 茶歇");
    AddNormal("15:30-17:00 | 模块六 | 高级辅导、有效授权与MAP");
    AddNormal("17:00-17:30 | 总结 | 课程总结，行为承诺");
    AddBreak();

    // Module 1
    AddH2("2.1 模块一：领导者角色与绩效管理体系");
    AddP("[模块时长：90分钟]", 12, false, 0x7D5151);
    AddBreak();
    AddH3("学习目标");
    AddNormal("• 理解领导者在绩效管理体系中的角色转变");
    AddNormal("• 掌握从\"任务分配者\"到\"绩效辅导者\"的角色转换");
    AddNormal("• 认识传统绩效评估的局限性");
    AddBreak();
    AddH3("知识要点");
    AddH4("【传统vs现代绩效管理】");
    AddNormal("传统模式：年度评估 → 评分 → 奖惩");
    AddNormal("现代模式：持续辅导 → 实时反馈 → 共同发展");
    AddBreak();
    AddH4("【管理者在绩效管理中的新角色】");
    AddNormal("1. 诊断者：了解团队成员的发展阶段和需求");
    AddNormal("2. 辅导者：通过辅导帮助员工提升能力");
    AddNormal("3. 反馈者：提供及时、具体、正向的反馈");
    AddNormal("4. 授权者：在合适的时机进行有效授权");
    AddBreak();
    AddH3("体验活动：月球会议");
    AddP("[时间：45分钟 | 物料：A3纸、月球地图、投票贴纸、计分表]", 12, false, 0x7D5151);
    AddBreak();
    AddH4("【活动流程】");
    AddNormal("1. 情境导入（5分钟）");
    AddNormal("2. 个人决策（10分钟）");
    AddNormal("3. 小组讨论与决策（15分钟）");
    AddNormal("4. 小组汇报与讲师点评（10分钟）");
    AddNormal("5. 反思总结（5分钟）");
    AddBreak();
    AddH3("常见学员问题及应答");
    AddNormal("Q: \"我们公司已经有了绩效考核系统，还需要辅导吗？\"");
    AddNormal("A: \"绩效考核系统解决的是'评估'问题，而辅导解决的是'发展'问题。两者相辅相成。\"");
    AddBreak();
    AddH3("重点/难点提示");
    AddNormal("[重点] 强调管理者角色的转变——从\"裁判\"到\"教练\"");
    AddNormal("[难点] 帮助学员理解\"辅导\"不是\"监控\"或\"检查\"，而是一种支持性对话");
    AddBreak();

    // Module 2
    AddH2("2.2 模块二：辅导入门：WHEN/HOW/Y");
    AddP("[模块时长：120分钟]", 12, false, 0x7D5151);
    AddBreak();
    AddH3("学习目标");
    AddNormal("• 掌握\"何时辅导\"（WHEN）的判断标准");
    AddNormal("• 学会\"如何辅导\"（HOW）的STAR模型");
    AddNormal("• 理解\"为什么辅导\"（Y）对员工动机的重要性");
    AddBreak();
    AddH3("核心模型：辅导三问");
    AddH4("【WHEN - 何时辅导】");
    AddNormal("• 绩效下降时：员工表现低于预期");
    AddNormal("• 发展机会时：新任务、新角色、新挑战");
    AddNormal("• 主动请求时：员工主动寻求反馈或帮助");
    AddNormal("• 关键转折时：职业发展、岗位变动、重要决策");
    AddBreak();
    AddH4("【HOW - 如何辅导：STAR模型】");
    AddNormal("• S - Situation：描述情境，提供背景");
    AddNormal("• T - Task：明确任务，说明期望");
    AddNormal("• A - Action：询问行动，了解过程");
    AddNormal("• R - Result：探讨结果，给予反馈");
    AddBreak();
    AddH4("【Y - 为什么辅导】");
    AddNormal("• 激发内在动机：帮助员工看到\"我为什么要做这件事\"");
    AddNormal("• 建立情感联结：通过辅导建立信任关系");
    AddNormal("• 创造意义感：让工作成为实现更大目标的途径");
    AddBreak();

    // Module 3
    AddH2("2.3 模块三：有效反馈：CAIR模型");
    AddP("[模块时长：90分钟]", 12, false, 0x7D5151);
    AddBreak();
    AddH3("CAIR模型");
    AddH4("【C - Context 情境】");
    AddNormal("• 提供具体的时间和情境");
    AddNormal("• \"昨天下午的团队会议上...\"");
    AddBreak();
    AddH4("【A - Action 行为】");
    AddNormal("• 描述具体可观察的行为");
    AddNormal("• \"你打断了小王的发言，然后直接提出了自己的方案\"");
    AddBreak();
    AddH4("【I - Impact 影响】");
    AddNormal("• 说明行为的影响");
    AddNormal("• \"这让小王有些尴尬，也影响了团队讨论的充分性\"");
    AddBreak();
    AddH4("【R - Request 请求】");
    AddNormal("• 提出具体的改变请求");
    AddNormal("• \"下次能否先让小王说完，你再做补充？\"");
    AddBreak();
    AddH3("角色扮演：反馈对话");
    AddP("[时间：30分钟 | 场景：经理向员工反馈其在项目汇报中的表现]", 12, false, 0x7D5151);
    AddBreak();

    // Module 4
    AddH2("2.4 模块四：困难谈话");
    AddP("[模块时长：90分钟]", 12, false, 0x7D5151);
    AddBreak();
    AddH3("困难谈话类型");
    AddNormal("• 绩效问题谈话");
    AddNormal("• 行为问题谈话");
    AddNormal("• 纪律处分谈话");
    AddNormal("• 裁员/降职谈话");
    AddNormal("• 处理冲突谈话");
    AddBreak();
    AddH3("准备框架：PLACE");
    AddNormal("• P - Purpose：明确谈话目的");
    AddNormal("• L - Logic：准备逻辑结构");
    AddNormal("• A - Anticipate：预判对方反应");
    AddNormal("• C - Compose：调整自己心态");
    AddNormal("• E - Evidence：准备具体证据");
    AddBreak();
    AddH3("谈话技巧");
    AddNormal("[开场] 先建立情感联结，再进入正题");
    AddNormal("[中段] 使用\"我\"开头的陈述，避免指责");
    AddNormal("[结尾] 明确下一步行动计划");
    AddBreak();

    // Module 5
    AddH2("2.5 模块五：联结沟通与工作关系");
    AddP("[模块时长：120分钟]", 12, false, 0x7D5151);
    AddBreak();
    AddH3("体验活动：三岛救援");
    AddP("[时间：60分钟 | 物料：三岛地图、角色卡、资源表、投票贴]", 12, false, 0x7D5151);
    AddBreak();
    AddH4("【活动流程】");
    AddNormal("1. 情境导入（10分钟）");
    AddNormal("2. 角色分配与任务理解（10分钟）");
    AddNormal("3. 岛屿内协商（20分钟）");
    AddNormal("4. 岛屿间谈判与交易（15分钟）");
    AddNormal("5. 结果揭晓与复盘（25分钟）");
    AddBreak();
    AddH3("核心概念：工作关系四层模型");
    AddNormal("[第一层：认识层] 知道对方是谁，点头之交");
    AddNormal("[第二层：交易层] 基于工作任务的互动");
    AddNormal("[第三层：合作层] 共同目标，主动互助");
    AddNormal("[第四层：联结层] 深度信任，全方位支持");
    AddBreak();

    // Module 6
    AddH2("2.6 模块六：高级辅导、有效授权与MAP");
    AddP("[模块时长：120分钟]", 12, false, 0x7D5151);
    AddBreak();
    AddH3("MAP模型");
    AddH4("【M - Measure 衡量】");
    AddNormal("• 明确衡量标准和成功指标");
    AddNormal("• \"我们如何知道任务完成了？\"");
    AddBreak();
    AddH4("【A - Align 对齐】");
    AddNormal("• 确保目标和方式的一致性");
    AddNormal("• \"这样做是否符合我们的价值观和原则？\"");
    AddBreak();
    AddH4("【P - Process 流程】");
    AddNormal("• 明确里程碑和检查点");
    AddNormal("• \"我们如何分阶段进行？何时检查进展？\"");
    AddBreak();
    AddH3("授权的层次");
    AddNormal("[层次一：执行] 告知具体做什么");
    AddNormal("[层次二：审批] 需要上级批准");
    AddNormal("[层次三：建议] 可以提建议，由上级决定");
    AddNormal("[层次四：同意] 可以行动，但需要上级同意");
    AddNormal("[层次五：自行决定] 完全自主决定");
    AddNormal("[层次六：委任] 将权力完全委托给下属");
    AddBreak();

    // Part 3
    AddH1("第三部分：体验活动完整设计");
    AddH2("3.1 月球会议（第一模块）");
    AddH3("活动概述");
    AddP("[活动名称] 月球会议 | [活动类型] 决策模拟 | [活动时间] 45分钟", 12);
    AddP("[活动目的] 体验领导者在资源受限情况下的决策困境，理解不同决策风格的利弊", 12);
    AddBreak();
    AddH3("物料清单");
    AddNormal("□ A3月球地图（每组1张）");
    AddNormal("□ 角色卡（每组6张）");
    AddNormal("□ 决策记录表（每组1份）");
    AddNormal("□ 投票贴纸（每组红、黄、绿各10张）");
    AddNormal("□ 白板/海报纸（用于小组汇报）");
    AddNormal("□ 计时器");
    AddBreak();
    AddH3("场景设置");
    AddH4("[情境设定]");
    AddNormal("1969年，阿波罗11号登月任务中，宇航员在月球表面遇到紧急状况。他们必须在限定时间内，从15件物品中选出5件最重要的，以便在月球表面生存并返回轨道。");
    AddBreak();
    AddH4("[任务目标]");
    AddNormal("小组需要在20分钟内达成共识，选择5件最重要的物品，并说明理由。");
    AddBreak();
    AddH4("[角色分配]（每组6人）");
    AddNormal("• 指挥官：负责最终决策");
    AddNormal("• 首席科学家：提供技术分析");
    AddNormal("• 通讯专家：负责记录和沟通");
    AddNormal("• 医生：关注人员安全");
    AddNormal("• 工程师：提供工程视角");
    AddNormal("• 财务官：评估资源成本");
    AddBreak();
    AddH3("引导话术");
    AddH4("[活动导入]");
    AddNormal("\"各位，欢迎来到1969年的NASA任务控制中心。我们刚刚收到阿波罗11号的紧急信号——宇航员在月球表面遇到了意外状况。现在，你们是地球上唯一能够帮助他们做出生死抉择的人。\"");
    AddBreak();
    AddH4("[规则说明]");
    AddNormal("\"你们有20分钟时间进行讨论和决策。请注意：1）每个角色必须发言；2）最终决策需要全组同意；3）请在决策记录表上写下你们的选择和理由。\"");
    AddBreak();
    AddH4("[时间提醒]");
    AddNormal("• 15分钟时：\"还剩5分钟，请开始形成共识\"");
    AddNormal("• 18分钟时：\"还剩2分钟，请做出最终决定\"");
    AddNormal("• 20分钟时：\"时间到，请停止讨论\"");
    AddBreak();
    AddH3("复盘问题");
    AddH4("[个人反思]");
    AddNormal("1. 在讨论过程中，你扮演了什么角色？");
    AddNormal("2. 你是否充分表达了你的观点？");
    AddNormal("3. 小组最终的决策是否体现了你的想法？");
    AddBreak();
    AddH4("[团队反思]");
    AddNormal("1. 小组是如何做出决策的？有没有发生冲突？如何解决的？");
    AddNormal("2. 小组中是否存在\"一言堂\"或\"沉默者\"？这对结果有什么影响？");
    AddNormal("3. 如果时间更紧/更充裕，结果会不同吗？");
    AddBreak();
    AddH4("[联系实际]");
    AddNormal("1. 这个活动与你工作中的哪些决策场景相似？");
    AddNormal("2. 作为领导者，你如何在有限信息和时间内做出高质量决策？");
    AddNormal("3. 你的团队在决策过程中是否存在类似的角色问题？");
    AddBreak();
    AddH3("时间控制");
    AddNormal("情境导入：5分钟 - 介绍背景，分配角色");
    AddNormal("个人决策：10分钟 - 分发材料，计时观察");
    AddNormal("小组讨论：15分钟 - 巡视各组，必要时引导");
    AddNormal("汇报点评：10分钟 - 邀请小组分享，讲师点评");
    AddNormal("总结延伸：5分钟 - 联系模块主题，总结要点");
    AddBreak();

    AddH2("3.2 三岛救援（第五模块）");
    AddH3("活动概述");
    AddP("[活动名称] 三岛救援 | [活动类型] 资源协调与谈判模拟 | [活动时间] 60分钟", 12);
    AddP("[活动目的] 体验跨部门协作的复杂性，理解联结沟通的重要性", 12);
    AddBreak();
    AddH3("物料清单");
    AddNormal("□ 三岛地图（每组1张）");
    AddNormal("□ 角色卡（每岛2-3张）");
    AddNormal("□ 资源交换协议表（每组3份）");
    AddNormal("□ 岛屿专属资源卡（每岛1套）");
    AddNormal("□ 紧急救援任务卡（每组1张）");
    AddNormal("□ 计时器");
    AddBreak();
    AddH3("场景设置");
    AddH4("[情境设定]");
    AddNormal("三座相邻的岛屿——能源岛、制造岛、科技岛——突然遭遇海啸袭击。三岛居民必须相互协作，共同完成紧急救援任务。每座岛屿拥有不同的专属资源，但救援任务需要多岛屿资源配合才能完成。");
    AddBreak();
    AddH4("[任务目标]");
    AddNormal("• 主要目标：在30分钟内完成紧急救援任务");
    AddNormal("• 次要目标：最大化各岛屿的生存资源");
    AddBreak();
    AddH4("[角色分配]（每组8-12人，分为3岛）");
    AddNormal("[能源岛]（2-4人）");
    AddNormal("• 岛屿领袖：负责对外谈判");
    AddNormal("• 能源专家：拥有电力和燃料专业知识");
    AddBreak();
    AddNormal("[制造岛]（2-4人）");
    AddNormal("• 岛屿领袖：负责对外谈判");
    AddNormal("• 生产专家：拥有物资生产专业知识");
    AddBreak();
    AddNormal("[科技岛]（2-4人）");
    AddNormal("• 岛屿领袖：负责对外谈判");
    AddNormal("• 技术专家：拥有医疗和通讯专业知识");
    AddBreak();

    // Part 4
    AddH1("第四部分：角色扮演完整设计");
    AddH2("角色扮演设计原则");
    AddNormal("UYLP课程中的角色扮演遵循以下设计原则：");
    AddNormal("1. 真实性：场景来源于真实工作情境");
    AddNormal("2. 安全性：创造一个允许犯错的学习环境");
    AddNormal("3. 聚焦性：每次角色扮演聚焦于一个特定技能");
    AddNormal("4. 循环性：练习 → 反馈 → 改进 → 再练习");
    AddBreak();

    AddH2("4.1 辅导对话角色扮演");
    AddP("[建议时长：45分钟（每组3轮，每轮15分钟）]", 12, false, 0x7D5151);
    AddBreak();
    AddH3("场景设定");
    AddP("[场景] 新晋经理小李辅导下属小王处理客户投诉", 12);
    AddP("[背景] 小王是客服部的一名资深员工，业务能力强，但最近连续收到两起客户投诉。经理小李需要与小王进行辅导对话。", 12);
    AddBreak();
    AddH3("角色背景");
    AddH4("[辅导员 - 小李]");
    AddNormal("• 角色：客服部新晋升的经理，3个月管理经验");
    AddNormal("• 目标：帮助小王找到问题根源，提升客户服务质量");
    AddNormal("• 顾虑：担心处理不好会伤害与小王的关系");
    AddBreak();
    AddH4("[被辅导者 - 小王]");
    AddNormal("• 角色：客服部资深员工，入职5年，连续两个月绩效优秀");
    AddNormal("• 目标：解释情况，希望得到理解和支持");
    AddNormal("• 顾虑：担心被质疑能力，影响晋升");
    AddBreak();
    AddH3("观察员指引");
    AddH4("[观察重点]");
    AddNormal("1. 辅导员是否建立了情感联结（Y）？");
    AddNormal("2. 是否使用了STAR模型（S-T-A-R四步是否完整）？");
    AddNormal("3. 辅导员是否在\"审问\"而非\"辅导\"？");
    AddNormal("4. 小王的反应是什么？辅导是否有效？");
    AddBreak();
    AddH4("[记录要点]");
    AddNormal("• 关键对话片段（记录原话）");
    AddNormal("• 辅导是否聚焦于行为而非人格");
    AddNormal("• 是否达成了具体的改进行动");
    AddBreak();
    AddH3("反馈指引");
    AddH4("[反馈顺序]");
    AddNormal("1. 先让辅导员分享感受：\"你觉得这次对话怎么样？\"");
    AddNormal("2. 再让被辅导者分享感受：\"你的感受是什么？\"");
    AddNormal("3. 观察员提供具体反馈（基于记录）");
    AddNormal("4. 讲师总结要点，引入改进建议");
    AddBreak();

    AddH2("4.2 反馈对话角色扮演");
    AddP("[建议时长：45分钟（每组3轮，每轮15分钟）]", 12, false, 0x7D5151);
    AddBreak();
    AddH3("场景设定");
    AddP("[场景] 项目经理张明向团队成员刘芳反馈其在项目汇报中的表现", 12);
    AddP("[背景] 刘芳在上周的项目汇报会上介绍了她负责的模块进展。她的汇报内容详实，但表达方式有些混乱，有时重复，有时跳跃。", 12);
    AddBreak();

    AddH2("4.3 困难谈话角色扮演");
    AddP("[建议时长：60分钟（每组3轮，每轮20分钟）]", 12, false, 0x7D5151);
    AddBreak();
    AddH3("场景设定");
    AddP("[场景] 部门总监陈总与即将被劝退的员工小周进行离职谈话", 12);
    AddP("[背景] 小周入职公司3年，担任市场专员。近半年绩效持续下滑，未能达到考核要求。公司决定与其协商解除劳动合同。", 12);
    AddBreak();
    AddH3("特别提示");
    AddH4("[讲师注意] 此场景涉及敏感话题，讲师需要：");
    AddNormal("• 在活动前强调\"这是学习场景，与真实情况不同\"");
    AddNormal("• 观察学员的情绪反应，必要时暂停活动");
    AddNormal("• 在复盘时强调\"同理心\"和\"尊重\"的重要性");
    AddNormal("• 不要评判学员的表现，而是引导自我反思");
    AddBreak();

    // Part 5
    AddH1("第五部分：讲师工具");
    AddH2("5.1 讲师时间控制表");
    AddH3("【Day 1】");
    AddNormal("08:30-09:00 签到与准备");
    AddNormal("09:00-09:15 开场");
    AddNormal("09:15-10:45 模块一");
    AddNormal("10:45-11:00 茶歇");
    AddNormal("11:00-12:30 模块二（上）");
    AddNormal("12:30-13:30 午餐");
    AddNormal("13:30-15:30 模块二（下）");
    AddNormal("15:30-15:45 茶歇");
    AddNormal("15:45-17:15 模块三");
    AddNormal("17:15-17:30 总结");
    AddBreak();
    AddH3("【Day 2】");
    AddNormal("08:30-09:00 签到与回顾");
    AddNormal("09:00-10:30 模块四");
    AddNormal("10:30-10:45 茶歇");
    AddNormal("10:45-12:15 模块五（上）");
    AddNormal("12:15-13:15 午餐");
    AddNormal("13:15-15:15 模块五（下）");
    AddNormal("15:15-15:30 茶歇");
    AddNormal("15:30-17:00 模块六");
    AddNormal("17:00-17:30 总结");
    AddBreak();

    AddH2("5.2 学员表现观察量表");
    AddNormal("讲师在授课过程中使用此量表观察学员表现，用于个性化反馈和课程调整。");
    AddBreak();
    AddH3("[观察量表模板]");
    AddNormal("学员姓名 | 模块 | 参与度 | 关键行为 | 发展建议");
    AddNormal("1 | 模块一 | 高/中/低 | | ");
    AddNormal("2 | 模块一 | 高/中/低 | | ");
    AddNormal("3 | 模块一 | 高/中/低 | | ");
    AddBreak();
    AddH3("[参与度评估标准]");
    AddNormal("高：主动发言，提出深刻问题，积极参与讨论和活动");
    AddNormal("中：偶尔发言，能够配合小组活动");
    AddNormal("低：很少发言或从不发言，需要特别关注");
    AddBreak();

    AddH2("5.3 课程评估指引");
    AddH3("评估层次");
    AddH4("[反应层] 学员对课程的满意度");
    AddNormal("• 评估方式：课后问卷");
    AddNormal("• 评估时点：课程结束");
    AddBreak();
    AddH4("[学习层] 学员是否掌握了知识和技能");
    AddNormal("• 评估方式：角色扮演表现、课堂讨论");
    AddNormal("• 评估时点：课程进行中");
    AddBreak();
    AddH4("[行为层] 学员是否将所学应用到工作中");
    AddNormal("• 评估方式：课后30天行为跟踪");
    AddNormal("• 评估时点：课程结束后30天");
    AddBreak();
    AddH4("[结果层] 课程对组织绩效的影响");
    AddNormal("• 评估方式：团队绩效指标对比");
    AddNormal("• 评估时点：课程结束后90天");
    AddBreak();

    AddH2("5.4 危机处理预案");
    AddH3("常见危机情况及处理方法");
    AddH4("[情况1：学员之间的冲突]");
    AddNormal("表现：两名学员在讨论中发生激烈争执");
    AddNormal("处理：");
    AddNormal("1. 保持冷静，不要立即站队");
    AddNormal("2. 说\"我看到你们有不同的观点，这很好。让我们听听各自的理由\"");
    AddNormal("3. 将焦点从\"对错\"转向\"学习\"");
    AddNormal("4. 如果冲突持续，私下分别沟通");
    AddBreak();
    AddH4("[情况2：学员情绪崩溃]");
    AddNormal("表现：学员因话题触及敏感点而情绪失控");
    AddNormal("处理：");
    AddNormal("1. 立即暂停活动");
    AddNormal("2. 私下关心询问：\"我注意到你有些情绪，是否需要休息一下？\"");
    AddNormal("3. 给予空间，不过度追问");
    AddNormal("4. 课后跟进关怀");
    AddBreak();
    AddH4("[情况3：活动参与度低]");
    AddNormal("表现：学员对活动缺乏投入，敷衍了事");
    AddNormal("处理：");
    AddNormal("1. 反思活动设计是否与学员需求匹配");
    AddNormal("2. 调整分组，将活跃学员与沉默学员搭配");
    AddNormal("3. 使用\"选择权\"技巧：\"你可以选择参与A或B，但不能不选择\"");
    AddNormal("4. 课后与个别学员交流了解原因");
    AddBreak();

    // Part 6
    AddH1("第六部分：附录");
    AddH2("6.1 核心模型速查");
    AddH3("辅导三问模型（WHEN/HOW/Y）");
    AddNormal("WHEN | 何时辅导 | 绩效下降时/发展机会时/主动请求时/关键转折时");
    AddNormal("HOW | 如何辅导（STAR）| S-情境/T-任务/A-行动/R-结果");
    AddNormal("Y | 为什么辅导 | 激发动机/建立联结/创造意义");
    AddBreak();
    AddH3("CAIR反馈模型");
    AddNormal("C - Context | 情境 | 昨天下午的团队会议上");
    AddNormal("A - Action | 行为 | 你打断了小王的发言");
    AddNormal("I - Impact | 影响 | 这让小王有些尴尬");
    AddNormal("R - Request | 请求 | 下次能否先让小王说完？");
    AddBreak();
    AddH3("MAP辅导模型");
    AddNormal("M - Measure | 衡量 | 我们如何知道任务完成了？");
    AddNormal("A - Align | 对齐 | 这样做是否符合价值观？");
    AddNormal("P - Process | 流程 | 如何分阶段进行？");
    AddBreak();
    AddH3("PLACE准备框架");
    AddNormal("P - Purpose | 明确谈话目的");
    AddNormal("L - Logic | 准备逻辑结构");
    AddNormal("A - Anticipate | 预判对方反应");
    AddNormal("C - Compose | 调整自己心态");
    AddNormal("E - Evidence | 准备具体证据");
    AddBreak();
    AddH3("授权层次模型");
    AddNormal("层次1：执行 | 告知具体做什么");
    AddNormal("层次2：审批 | 需要上级批准");
    AddNormal("层次3：建议 | 可以提建议，由上级决定");
    AddNormal("层次4：同意 | 可以行动，但需要上级同意");
    AddNormal("层次5：自行决定 | 完全自主决定");
    AddNormal("层次6：委任 | 将权力完全委托给下属");
    AddBreak();

    AddH2("6.2 参考资料");
    AddH3("【书籍】");
    AddNormal("1. 《非暴力沟通》- 马歇尔·卢森堡");
    AddNormal("2. 《教练式辅导》- 希尔维亚·希尔德");
    AddNormal("3. 《高绩效教练》- 约翰·惠特莫尔");
    AddNormal("4. 《关键对话》- 科里·帕特森等");
    AddNormal("5. 《联盟》- 里德·霍夫曼等");
    AddBreak();
    AddH3("【模型来源】");
    AddNormal("1. STAR模型：源于教练技术（Gallwey《高绩效教练》）");
    AddNormal("2. CAIR模型：源于绩效反馈最佳实践");
    AddNormal("3. 体验式学习循环：Kolb（科尔布）经验学习理论");
    AddBreak();

    AddH2("6.3 术语表");
    AddNormal("术语 | 英文 | 定义");
    AddNormal("辅导 | Coaching | 通过对话支持员工发展能力和绩效的管理行为");
    AddNormal("反馈 | Feedback | 对他人行为提供信息以帮助其改进的过程");
    AddNormal("授权 | Empowerment | 将决策权下放给下属的管理实践");
    AddNormal("绩效管理 | Performance Management | 持续提升个体和团队绩效的系统方法");
    AddNormal("困难谈话 | Difficult Conversation | 涉及敏感话题需要谨慎处理的沟通");
    AddNormal("联结沟通 | Connective Communication | 建立和维护工作关系的沟通方式");
    AddNormal("角色扮演 | Role Play | 模拟真实场景进行练习的教学方法");
    AddNormal("体验式学习 | Experiential Learning | 通过亲身体验和反思进行学习的方法");
    AddBreak();
    AddBreak();
    AddP("—— 手册结束 ——", 14, true);

    mainPart.Document.Save();
}

// Write memory stream to file
File.WriteAllBytes(outputPath, ms.ToArray());
Console.WriteLine($"Document saved to: {outputPath}");
Console.WriteLine($"File size: {new FileInfo(outputPath).Length} bytes");